#!/usr/bin/env python3
"""Monta o dossiê de revisão de uma entrega.

Duas metades, e a divisão é deliberada:

* o que a **máquina** sabe — commits, arquivos, e a saída literal dos comandos
  de verificação — é coletado aqui e não passa pela memória de ninguém;
* o que só o **autor** sabe — o que não foi verificado, que premissas sobre o
  ambiente ele assumiu, onde hesitou — fica marcado como pendência no arquivo,
  e `--conferir` recusa o dossiê enquanto qualquer marca continuar lá.

A regra que sustenta tudo: **afirmação de medição precisa de saída de comando
colada**. O que não tem saída não é medição — é suposição, e vai para a seção
das suposições por construção, não por virtude do autor.

Uso:
    python3 .claude/skills/revisao/dossie.py --desde <ref>   # gera
    python3 .claude/skills/revisao/dossie.py --conferir      # valida
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

#: Sequências de cor do terminal. Elas tornam a saída ilegível dentro de um
#: `.md`, e o dossiê existe para ser lido — inclusive por quem não o abriu num
#: terminal.
ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")

RAIZ = pathlib.Path(__file__).resolve().parents[3]
COMANDOS = pathlib.Path(__file__).with_name("comandos.txt")
DESTINO = RAIZ / "REVISAO.md"

#: Marca que o autor precisa substituir. O dossiê não fecha com ela dentro.
PENDENTE = "<<PREENCHER>>"

#: Como um arquivo gerado se anuncia. Um arquivo que traz isto nas primeiras
#: linhas é **derivado**: revisá-lo linha a linha é revisar a saída de um
#: programa em vez do programa.
MARCAS_DE_GERADO = ("gerado por", "generated by", "não edite", "do not edit")


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=RAIZ, capture_output=True, text=True, check=True
    ).stdout.strip()


def _e_gerado(caminho: str) -> bool:
    arquivo = RAIZ / caminho
    if not arquivo.is_file():
        return False
    try:
        cabecalho = "".join(arquivo.open(encoding="utf-8").readlines()[:6]).lower()
    except (UnicodeDecodeError, OSError):
        return False
    return any(marca in cabecalho for marca in MARCAS_DE_GERADO)


def _comandos() -> list[str]:
    if not COMANDOS.exists():
        COMANDOS.write_text(
            "# Comandos de verificação deste projeto, um por linha.\n"
            "# O dossiê roda cada um e cola a saída. Linha com # é ignorada.\n"
            "# Exemplos: make test · make dbt-build · make lint\n",
            encoding="utf-8",
        )
        return []
    return [
        linha.strip()
        for linha in COMANDOS.read_text(encoding="utf-8").splitlines()
        if linha.strip() and not linha.strip().startswith("#")
    ]


def _executar(comando: str, segundos: int) -> tuple[int, str]:
    try:
        saida = subprocess.run(
            comando, shell=True, cwd=RAIZ, capture_output=True, text=True, timeout=segundos
        )
    except subprocess.TimeoutExpired:
        return 124, f"(estourou {segundos}s sem terminar)"
    limpo = ANSI.sub("", saida.stdout + saida.stderr).strip()
    linhas = [l.rstrip() for l in limpo.splitlines() if l.strip()]
    return saida.returncode, "\n".join(linhas[-12:]) or "(sem saída)"


def gerar(desde: str, segundos: int) -> pathlib.Path:
    # O topo é **fixado** no SHA, não deixado como `HEAD`. Um dossiê que diz
    # `base..HEAD` passa a descrever outro intervalo assim que um commit novo
    # entra — e quem revisa lê o diff errado sem perceber, porque a lista de
    # commits do dossiê continua parecendo certa.
    ate = _git("rev-parse", "--short", "HEAD")
    commits = _git("log", "--reverse", "--format=%h %s", f"{desde}..{ate}")
    if not commits:
        sys.exit(f"nenhum commit em {desde}..HEAD — nada a revisar")

    arquivos = [
        linha.split("\t", 1)[1]
        for linha in _git("diff", "--name-status", f"{desde}..{ate}").splitlines()
        if "\t" in linha
    ]
    gerados = [a for a in arquivos if _e_gerado(a)]
    escritos = [a for a in arquivos if a not in gerados]

    execucoes = []
    for comando in _comandos():
        codigo, saida = _executar(comando, segundos)
        execucoes.append((comando, codigo, saida))

    partes = [
        "# Revisão da entrega",
        "",
        "> Dossiê gerado por `.claude/skills/revisao/dossie.py`. **Transitório**: sai no *commit*",
        "> que fecha a revisão. Não é documentação do projeto e não entra no mapa do README.",
        ">",
        "> **É um convite, não uma ordem.** Ele não substitui o que o Owner pediu nesta sessão: se",
        "> o pedido foi implementar, implemente — este arquivo continua aqui esperando quem revisar.",
        "",
        "## 1. Escopo",
        "",
        f"Intervalo: `{desde}..{ate}` — leia o diff, ele não é repetido aqui.",
        "",
        "Os dois extremos são SHA fixos de propósito: um dossiê que dissesse `..HEAD` passaria a",
        "descrever outro intervalo no primeiro *commit* seguinte, sem que a lista abaixo mudasse.",
        "",
        "```",
        commits,
        "```",
        "",
        "## 2. Mapa de revisão",
        "",
        "Onde gastar esforço. **Erro em derivado é sintoma: corrige-se na declaração.**",
        "",
        f"### Escritos à mão — {len(escritos)} arquivos",
        "",
        *(f"- `{a}`" for a in escritos),
        "",
        f"### Gerados — {len(gerados)} arquivos, revisar por amostragem",
        "",
        *(f"- `{a}`" for a in gerados or ["(nenhum)"]),
        "",
        f"**Declaração desta entrega:** {PENDENTE} — quais destes arquivos são a *declaração*",
        "de que os demais nascem, e que por isso pedem revisão integral.",
        "",
        "## 3. O que foi medido",
        "",
        "Saída literal, não resumo. Comando sem saída aqui não é medição.",
        "",
    ]

    for comando, codigo, saida in execucoes:
        marca = "✓" if codigo == 0 else f"✗ (código {codigo})"
        partes += [f"### `{comando}` {marca}", "", "```", saida, "```", ""]
    if not execucoes:
        partes += [
            f"{PENDENTE} — nenhum comando declarado em",
            "`.claude/skills/revisao/comandos.txt`. Sem isso, **nada** nesta entrega está medido.",
            "",
        ]

    partes += [
        "## 4. O que NÃO foi verificado",
        "",
        "A seção mais útil do dossiê, e a que o autor tem menos vontade de escrever.",
        "Toda afirmação sem saída de comando na seção 3 pertence aqui.",
        "",
        f"{PENDENTE}",
        "",
        "## 5. Premissas sobre o ambiente",
        "",
        "O que foi assumido sobre ferramenta, banco ou serviço e **não** foi confirmado nesta",
        "entrega. É a classe de erro que passa por revisão de código sem ser vista.",
        "",
        f"{PENDENTE}",
        "",
        "## 6. Onde hesitei",
        "",
        "Decisões que poderiam ter ido para o outro lado, com o motivo de terem ido para este.",
        "",
        f"{PENDENTE}",
        "",
        "---",
        "",
        "## Achados da revisão",
        "",
        "Preenchido por quem revisa. Um achado por linha, com veredito.",
        "",
        "| # | Onde | Achado | Veredito | Situação |",
        "|---|---|---|---|---|",
        "| | | | `bloqueante` · `ajuste` · `observação` | |",
        "",
    ]

    DESTINO.write_text("\n".join(partes) + "\n", encoding="utf-8")
    return DESTINO


def conferir() -> int:
    if not DESTINO.exists():
        print(f"sem dossiê em {DESTINO.relative_to(RAIZ)}")
        return 1
    texto = DESTINO.read_text(encoding="utf-8")
    pendencias = texto.count(PENDENTE)
    falhas = texto.count("✗")
    if pendencias:
        print(f"{pendencias} seção(ões) ainda com {PENDENTE} — o dossiê não está pronto")
        return 1
    if falhas:
        print(f"{falhas} comando(s) de verificação falharam; explique cada um antes de passar")
        return 1
    print("dossiê completo: sem pendências e sem verificação falhando")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Dossiê de revisão de uma entrega.")
    parser.add_argument("--desde", help="ref a partir da qual comparar, ex.: origin/main")
    parser.add_argument("--timeout", type=int, default=1800, help="segundos por comando")
    parser.add_argument("--conferir", action="store_true", help="valida o dossiê existente")
    args = parser.parse_args()

    if args.conferir:
        return conferir()
    if not args.desde:
        parser.error("informe --desde <ref> ou --conferir")
    caminho = gerar(args.desde, args.timeout)
    print(f"dossiê em {caminho.relative_to(RAIZ)} — preencha as seções marcadas com {PENDENTE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
