-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  GERADO por `make legacy-models` a partir de src/mvp_ed1/legacy/         ║
-- ║  catalogo.yml. Não edite este arquivo: a próxima geração o sobrescreve.  ║
-- ║  Erro aqui é sintoma — corrija no catálogo ou em `regras.py`.            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- Limpeza de `legacy.orders` — camada `staging` (ADR-0016).
--
-- Uma linha por ocorrência física da **captura mais recente**. Reter capturas
-- antigas (ADR-0037) não significa somá-las: o tratamento olha a última, e as
-- anteriores existem para comparação e reprocessamento.
--
-- Duas saídas por coluna: o valor tratado e o **achado**, que é o código da
-- primeira falha que casa. O valor original permanece acessível em
-- `raw_legacy`, que é imutável.

with captura as (

    select *
    from {{ source('legacy', 'orders') }}
    -- A captura é escolhida **uma vez**, em `legacy_selected_capture`, e não
    -- aqui. O máximo por tabela parecia equivalente e não é: uma tabela que
    -- não veio na carga nova cairia para a geração anterior sozinha, e o
    -- modelo serviria linhas velhas sem que nada dissesse isso.
    where _airbyte_generation_id = (
        select snapshot_id from {{ ref('legacy_selected_capture') }}
    )

),

-- A limpeza vem **antes** dos achados, e não junto: o achado de rejeição
-- precisa ser conferido contra o valor já convertido, senão uma conversão
-- bem-sucedida esconde a invalidade do resultado dela.
limpo as (

    select
        c.legacy_row_id,
        case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            else c."id"
        end as "id",
        case
            when btrim(c."order_number") = '' or btrim(c."order_number") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."order_number" like '%;%' and (c."customer_id" is null or btrim(c."customer_id") = '') and (c."sales_channel_id" is null or btrim(c."sales_channel_id") = '') then c."order_number"
            when c."order_number" ~ '(Ã[-¿]|Â[-¿])' and c."order_number" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."order_number", 'LATIN1'), 'UTF8')
            when c."order_number" <> btrim(c."order_number") or c."order_number" ~ '  ' then regexp_replace(btrim(c."order_number"), '\s+', ' ', 'g')
            else c."order_number"
        end as "order_number",
        c."customer_id" as "customer_id",
        c."sales_channel_id" as "sales_channel_id",
        c."cart_id" as "cart_id",
        case
            when btrim(c."status") = '' or btrim(c."status") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(c."status") not in ('pending', 'paid', 'picking', 'shipped', 'delivered', 'cancelled', 'returned') then c."status"
            else c."status"
        end as "status",
        case
            when btrim(c."placed_at") = '' or btrim(c."placed_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."placed_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."placed_at" from 6 for 2)::int between 1 and 12 and substring(c."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 9 for 2)::int > 30) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int > 29) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int = 29 and not (substring(c."placed_at" from 1 for 4)::int % 4 = 0 and (substring(c."placed_at" from 1 for 4)::int % 100 <> 0 or substring(c."placed_at" from 1 for 4)::int % 400 = 0)))) when c."placed_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."placed_at" from 4 for 2)::int between 1 and 12 and substring(c."placed_at" from 1 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 1 for 2)::int > 30) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int > 29) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int = 29 and not (substring(c."placed_at" from 7 for 4)::int % 4 = 0 and (substring(c."placed_at" from 7 for 4)::int % 100 <> 0 or substring(c."placed_at" from 7 for 4)::int % 400 = 0)))) when c."placed_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."placed_at"
            when case when c."placed_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."placed_at" from 6 for 2)::int between 1 and 12 and substring(c."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 9 for 2)::int > 30) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int > 29) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int = 29 and not (substring(c."placed_at" from 1 for 4)::int % 4 = 0 and (substring(c."placed_at" from 1 for 4)::int % 100 <> 0 or substring(c."placed_at" from 1 for 4)::int % 400 = 0)))) then left(c."placed_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."placed_at"
            when case when c."placed_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."placed_at" from 4 for 2)::int between 1 and 12 and substring(c."placed_at" from 1 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 1 for 2)::int > 30) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int > 29) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int = 29 and not (substring(c."placed_at" from 7 for 4)::int % 4 = 0 and (substring(c."placed_at" from 7 for 4)::int % 100 <> 0 or substring(c."placed_at" from 7 for 4)::int % 400 = 0)))) when c."placed_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."placed_at" from 6 for 2)::int between 1 and 12 and substring(c."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 9 for 2)::int > 30) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int > 29) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int = 29 and not (substring(c."placed_at" from 1 for 4)::int % 4 = 0 and (substring(c."placed_at" from 1 for 4)::int % 100 <> 0 or substring(c."placed_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."placed_at" ~ '^[0-9]{2}/' then to_date(c."placed_at", 'DD/MM/YYYY')::text else to_date(c."placed_at", 'YYYY.MM.DD')::text end
            when c."placed_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."placed_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."placed_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."placed_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."placed_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."placed_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."placed_at"
            else c."placed_at"
        end as "placed_at",
        case
            when btrim(c."currency") = '' or btrim(c."currency") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."currency" like '%;%' and (c."subtotal_amount" is null or btrim(c."subtotal_amount") = '') and (c."discount_amount" is null or btrim(c."discount_amount") = '') then c."currency"
            when c."currency" ~ '(Ã[-¿]|Â[-¿])' and c."currency" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."currency", 'LATIN1'), 'UTF8')
            when c."currency" <> btrim(c."currency") or c."currency" ~ '  ' then regexp_replace(btrim(c."currency"), '\s+', ' ', 'g')
            else c."currency"
        end as "currency",
        case
            when btrim(c."subtotal_amount") = '' or btrim(c."subtotal_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."subtotal_amount", 'R$', ''), ' ', '')) ~ '^-' then c."subtotal_amount"
            when c."subtotal_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."subtotal_amount", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."subtotal_amount", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."subtotal_amount", 'R$', ''), ' ', ''), ',', '') end
            when c."subtotal_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."subtotal_amount"
            else c."subtotal_amount"
        end as "subtotal_amount",
        case
            when btrim(c."discount_amount") = '' or btrim(c."discount_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."discount_amount", 'R$', ''), ' ', '')) ~ '^-' then c."discount_amount"
            when c."discount_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."discount_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."discount_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."discount_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."discount_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."discount_amount", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."discount_amount", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."discount_amount", 'R$', ''), ' ', ''), ',', '') end
            when c."discount_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."discount_amount"
            else c."discount_amount"
        end as "discount_amount",
        case
            when btrim(c."shipping_amount") = '' or btrim(c."shipping_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."shipping_amount", 'R$', ''), ' ', '')) ~ '^-' then c."shipping_amount"
            when c."shipping_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."shipping_amount", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."shipping_amount", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."shipping_amount", 'R$', ''), ' ', ''), ',', '') end
            when c."shipping_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."shipping_amount"
            else c."shipping_amount"
        end as "shipping_amount",
        case
            when btrim(c."tax_amount") = '' or btrim(c."tax_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."tax_amount", 'R$', ''), ' ', '')) ~ '^-' then c."tax_amount"
            when c."tax_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."tax_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."tax_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."tax_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."tax_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."tax_amount", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."tax_amount", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."tax_amount", 'R$', ''), ' ', ''), ',', '') end
            when c."tax_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."tax_amount"
            else c."tax_amount"
        end as "tax_amount",
        case
            when btrim(c."total_amount") = '' or btrim(c."total_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."total_amount", 'R$', ''), ' ', '')) ~ '^-' then c."total_amount"
            when c."total_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."total_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."total_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."total_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."total_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."total_amount", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."total_amount", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."total_amount", 'R$', ''), ' ', ''), ',', '') end
            when c."total_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."total_amount"
            else c."total_amount"
        end as "total_amount",
        case
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."created_at" ~ '^[0-9]{2}/' then to_date(c."created_at", 'DD/MM/YYYY')::text else to_date(c."created_at", 'YYYY.MM.DD')::text end
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."created_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."created_at"
            else c."created_at"
        end as "created_at",
        case
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."updated_at" ~ '^[0-9]{2}/' then to_date(c."updated_at", 'DD/MM/YYYY')::text else to_date(c."updated_at", 'YYYY.MM.DD')::text end
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."updated_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."updated_at"
            else c."updated_at"
        end as "updated_at",
        case
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."deleted_at" ~ '^[0-9]{2}/' then to_date(c."deleted_at", 'DD/MM/YYYY')::text else to_date(c."deleted_at", 'YYYY.MM.DD')::text end
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."deleted_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."deleted_at"
            else c."deleted_at"
        end as "deleted_at"
    from captura c

)

select
    c.legacy_row_id,
    c._airbyte_generation_id                    as snapshot_id,
    c._airbyte_extracted_at                     as snapshot_at,
    'legacy'                                    as source_system,

    -- ── Valores tratados ─────────────────────────────────────────────────────
    l."id",
    l."order_number",
    l."customer_id",
    l."sales_channel_id",
    l."cart_id",
    l."status",
    l."placed_at",
    l."currency",
    l."subtotal_amount",
    l."discount_amount",
    l."shipping_amount",
    l."tax_amount",
    l."total_amount",
    l."created_at",
    l."updated_at",
    l."deleted_at",

    -- ── Achados por coluna, sem os nulos ─────────────────────────────────────
    jsonb_strip_nulls(
        jsonb_build_object(
            'id', case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
        end,
            'order_number', case
            when btrim(c."order_number") = '' or btrim(c."order_number") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."order_number" like '%;%' and (c."customer_id" is null or btrim(c."customer_id") = '') and (c."sales_channel_id" is null or btrim(c."sales_channel_id") = '') then 'TEXT_DELIMITER'
            when c."order_number" ~ '(Ã[-¿]|Â[-¿])' and c."order_number" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."order_number" <> btrim(c."order_number") or c."order_number" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'status', case
            when btrim(l."status") not in ('pending', 'paid', 'picking', 'shipped', 'delivered', 'cancelled', 'returned') then 'ENUM_UNKNOWN'
            when btrim(c."status") = '' or btrim(c."status") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(c."status") not in ('pending', 'paid', 'picking', 'shipped', 'delivered', 'cancelled', 'returned') then 'ENUM_UNKNOWN'
        end,
            'placed_at', case
            when case when l."placed_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."placed_at" from 6 for 2)::int between 1 and 12 and substring(l."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(l."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."placed_at" from 9 for 2)::int > 30) and not (substring(l."placed_at" from 6 for 2)::int = 2 and substring(l."placed_at" from 9 for 2)::int > 29) and not (substring(l."placed_at" from 6 for 2)::int = 2 and substring(l."placed_at" from 9 for 2)::int = 29 and not (substring(l."placed_at" from 1 for 4)::int % 4 = 0 and (substring(l."placed_at" from 1 for 4)::int % 100 <> 0 or substring(l."placed_at" from 1 for 4)::int % 400 = 0)))) when l."placed_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."placed_at" from 4 for 2)::int between 1 and 12 and substring(l."placed_at" from 1 for 2)::int between 1 and 31 and not (substring(l."placed_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."placed_at" from 1 for 2)::int > 30) and not (substring(l."placed_at" from 4 for 2)::int = 2 and substring(l."placed_at" from 1 for 2)::int > 29) and not (substring(l."placed_at" from 4 for 2)::int = 2 and substring(l."placed_at" from 1 for 2)::int = 29 and not (substring(l."placed_at" from 7 for 4)::int % 4 = 0 and (substring(l."placed_at" from 7 for 4)::int % 100 <> 0 or substring(l."placed_at" from 7 for 4)::int % 400 = 0)))) when l."placed_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."placed_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."placed_at" from 6 for 2)::int between 1 and 12 and substring(l."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(l."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."placed_at" from 9 for 2)::int > 30) and not (substring(l."placed_at" from 6 for 2)::int = 2 and substring(l."placed_at" from 9 for 2)::int > 29) and not (substring(l."placed_at" from 6 for 2)::int = 2 and substring(l."placed_at" from 9 for 2)::int = 29 and not (substring(l."placed_at" from 1 for 4)::int % 4 = 0 and (substring(l."placed_at" from 1 for 4)::int % 100 <> 0 or substring(l."placed_at" from 1 for 4)::int % 400 = 0)))) then left(l."placed_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."placed_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."placed_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."placed_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."placed_at") = '' or btrim(c."placed_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."placed_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."placed_at" from 6 for 2)::int between 1 and 12 and substring(c."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 9 for 2)::int > 30) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int > 29) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int = 29 and not (substring(c."placed_at" from 1 for 4)::int % 4 = 0 and (substring(c."placed_at" from 1 for 4)::int % 100 <> 0 or substring(c."placed_at" from 1 for 4)::int % 400 = 0)))) when c."placed_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."placed_at" from 4 for 2)::int between 1 and 12 and substring(c."placed_at" from 1 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 1 for 2)::int > 30) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int > 29) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int = 29 and not (substring(c."placed_at" from 7 for 4)::int % 4 = 0 and (substring(c."placed_at" from 7 for 4)::int % 100 <> 0 or substring(c."placed_at" from 7 for 4)::int % 400 = 0)))) when c."placed_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."placed_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."placed_at" from 6 for 2)::int between 1 and 12 and substring(c."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 9 for 2)::int > 30) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int > 29) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int = 29 and not (substring(c."placed_at" from 1 for 4)::int % 4 = 0 and (substring(c."placed_at" from 1 for 4)::int % 100 <> 0 or substring(c."placed_at" from 1 for 4)::int % 400 = 0)))) then left(c."placed_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."placed_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."placed_at" from 4 for 2)::int between 1 and 12 and substring(c."placed_at" from 1 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 1 for 2)::int > 30) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int > 29) and not (substring(c."placed_at" from 4 for 2)::int = 2 and substring(c."placed_at" from 1 for 2)::int = 29 and not (substring(c."placed_at" from 7 for 4)::int % 4 = 0 and (substring(c."placed_at" from 7 for 4)::int % 100 <> 0 or substring(c."placed_at" from 7 for 4)::int % 400 = 0)))) when c."placed_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."placed_at" from 6 for 2)::int between 1 and 12 and substring(c."placed_at" from 9 for 2)::int between 1 and 31 and not (substring(c."placed_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."placed_at" from 9 for 2)::int > 30) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int > 29) and not (substring(c."placed_at" from 6 for 2)::int = 2 and substring(c."placed_at" from 9 for 2)::int = 29 and not (substring(c."placed_at" from 1 for 4)::int % 4 = 0 and (substring(c."placed_at" from 1 for 4)::int % 100 <> 0 or substring(c."placed_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."placed_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."placed_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."placed_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."placed_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."placed_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'currency', case
            when btrim(c."currency") = '' or btrim(c."currency") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."currency" like '%;%' and (c."subtotal_amount" is null or btrim(c."subtotal_amount") = '') and (c."discount_amount" is null or btrim(c."discount_amount") = '') then 'TEXT_DELIMITER'
            when c."currency" ~ '(Ã[-¿]|Â[-¿])' and c."currency" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."currency" <> btrim(c."currency") or c."currency" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'subtotal_amount', case
            when btrim(replace(replace(l."subtotal_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when l."subtotal_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
            when btrim(c."subtotal_amount") = '' or btrim(c."subtotal_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."subtotal_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."subtotal_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."subtotal_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."subtotal_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'discount_amount', case
            when btrim(replace(replace(l."discount_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when l."discount_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
            when btrim(c."discount_amount") = '' or btrim(c."discount_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."discount_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."discount_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."discount_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."discount_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."discount_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."discount_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."discount_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'shipping_amount', case
            when btrim(replace(replace(l."shipping_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when l."shipping_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
            when btrim(c."shipping_amount") = '' or btrim(c."shipping_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."shipping_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."shipping_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."shipping_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."shipping_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'tax_amount', case
            when btrim(replace(replace(l."tax_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when l."tax_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
            when btrim(c."tax_amount") = '' or btrim(c."tax_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."tax_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."tax_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."tax_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."tax_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."tax_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."tax_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."tax_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'total_amount', case
            when btrim(replace(replace(l."total_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when l."total_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
            when btrim(c."total_amount") = '' or btrim(c."total_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."total_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."total_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."total_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."total_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."total_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."total_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."total_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'created_at', case
            when case when l."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."created_at" from 6 for 2)::int between 1 and 12 and substring(l."created_at" from 9 for 2)::int between 1 and 31 and not (substring(l."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 9 for 2)::int > 30) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int > 29) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int = 29 and not (substring(l."created_at" from 1 for 4)::int % 4 = 0 and (substring(l."created_at" from 1 for 4)::int % 100 <> 0 or substring(l."created_at" from 1 for 4)::int % 400 = 0)))) when l."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."created_at" from 4 for 2)::int between 1 and 12 and substring(l."created_at" from 1 for 2)::int between 1 and 31 and not (substring(l."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 1 for 2)::int > 30) and not (substring(l."created_at" from 4 for 2)::int = 2 and substring(l."created_at" from 1 for 2)::int > 29) and not (substring(l."created_at" from 4 for 2)::int = 2 and substring(l."created_at" from 1 for 2)::int = 29 and not (substring(l."created_at" from 7 for 4)::int % 4 = 0 and (substring(l."created_at" from 7 for 4)::int % 100 <> 0 or substring(l."created_at" from 7 for 4)::int % 400 = 0)))) when l."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."created_at" from 6 for 2)::int between 1 and 12 and substring(l."created_at" from 9 for 2)::int between 1 and 31 and not (substring(l."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 9 for 2)::int > 30) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int > 29) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int = 29 and not (substring(l."created_at" from 1 for 4)::int % 4 = 0 and (substring(l."created_at" from 1 for 4)::int % 100 <> 0 or substring(l."created_at" from 1 for 4)::int % 400 = 0)))) then left(l."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'updated_at', case
            when case when l."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."updated_at" from 6 for 2)::int between 1 and 12 and substring(l."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 9 for 2)::int > 30) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int > 29) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int = 29 and not (substring(l."updated_at" from 1 for 4)::int % 4 = 0 and (substring(l."updated_at" from 1 for 4)::int % 100 <> 0 or substring(l."updated_at" from 1 for 4)::int % 400 = 0)))) when l."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."updated_at" from 4 for 2)::int between 1 and 12 and substring(l."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 1 for 2)::int > 30) and not (substring(l."updated_at" from 4 for 2)::int = 2 and substring(l."updated_at" from 1 for 2)::int > 29) and not (substring(l."updated_at" from 4 for 2)::int = 2 and substring(l."updated_at" from 1 for 2)::int = 29 and not (substring(l."updated_at" from 7 for 4)::int % 4 = 0 and (substring(l."updated_at" from 7 for 4)::int % 100 <> 0 or substring(l."updated_at" from 7 for 4)::int % 400 = 0)))) when l."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."updated_at" from 6 for 2)::int between 1 and 12 and substring(l."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 9 for 2)::int > 30) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int > 29) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int = 29 and not (substring(l."updated_at" from 1 for 4)::int % 4 = 0 and (substring(l."updated_at" from 1 for 4)::int % 100 <> 0 or substring(l."updated_at" from 1 for 4)::int % 400 = 0)))) then left(l."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'deleted_at', case
            when case when l."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."deleted_at" from 6 for 2)::int between 1 and 12 and substring(l."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 9 for 2)::int > 30) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int > 29) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int = 29 and not (substring(l."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 1 for 4)::int % 400 = 0)))) when l."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."deleted_at" from 4 for 2)::int between 1 and 12 and substring(l."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 1 for 2)::int > 30) and not (substring(l."deleted_at" from 4 for 2)::int = 2 and substring(l."deleted_at" from 1 for 2)::int > 29) and not (substring(l."deleted_at" from 4 for 2)::int = 2 and substring(l."deleted_at" from 1 for 2)::int = 29 and not (substring(l."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 7 for 4)::int % 400 = 0)))) when l."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."deleted_at" from 6 for 2)::int between 1 and 12 and substring(l."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 9 for 2)::int > 30) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int > 29) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int = 29 and not (substring(l."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(l."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end
        )
    )                                           as achados,
    jsonb_build_object('id', c."id", 'order_number', c."order_number", 'customer_id', c."customer_id", 'sales_channel_id', c."sales_channel_id", 'cart_id', c."cart_id", 'status', c."status", 'placed_at', c."placed_at", 'currency', c."currency", 'subtotal_amount', c."subtotal_amount", 'discount_amount', c."discount_amount", 'shipping_amount', c."shipping_amount", 'tax_amount', c."tax_amount", 'total_amount', c."total_amount", 'created_at', c."created_at", 'updated_at', c."updated_at", 'deleted_at', c."deleted_at")              as original_payload
from captura c
join limpo l on l.legacy_row_id = c.legacy_row_id
