-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  GERADO por `make legacy-models` a partir de src/mvp_ed1/legacy/         ║
-- ║  catalogo.yml. Não edite este arquivo: a próxima geração o sobrescreve.  ║
-- ║  Erro aqui é sintoma — corrija no catálogo ou em `regras.py`.            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- Limpeza de `legacy.payments` — camada `staging` (ADR-0016).
--
-- Uma linha por ocorrência física da **captura mais recente**. Reter capturas
-- antigas (ADR-0037) não significa somá-las: o tratamento olha a última, e as
-- anteriores existem para comparação e reprocessamento.
--
-- Duas saídas por coluna: o valor tratado e o **achado**, que é o código da
-- primeira falha que casa. O valor original permanece acessível em
-- `raw_legacy`, que é imutável.

with captura as (

    select *
    from {{ source('legacy', 'payments') }}
    -- A captura é escolhida **uma vez**, em `legacy_selected_capture`, e não
    -- aqui. O máximo por tabela parecia equivalente e não é: uma tabela que
    -- não veio na carga nova cairia para a geração anterior sozinha, e o
    -- modelo serviria linhas velhas sem que nada dissesse isso.
    where _airbyte_generation_id = (
        select snapshot_id from {{ ref('legacy_selected_capture') }}
    )

),

-- A limpeza vem **antes** dos achados, e não junto: o achado de rejeição
-- precisa ser conferido contra o valor já convertido, senão uma conversão
-- bem-sucedida esconde a invalidade do resultado dela.
limpo as (

    select
        c.legacy_row_id,
        case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            else c."id"
        end as "id",
        case
            when btrim(c."payment_code") = '' or btrim(c."payment_code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."payment_code" like '%;%' and (c."order_id" is null or btrim(c."order_id") = '') and (c."payment_method_id" is null or btrim(c."payment_method_id") = '') then c."payment_code"
            when c."payment_code" ~ '(Ã[-¿]|Â[-¿])' and c."payment_code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."payment_code", 'LATIN1'), 'UTF8')
            when c."payment_code" <> btrim(c."payment_code") or c."payment_code" ~ '  ' then regexp_replace(btrim(c."payment_code"), '\s+', ' ', 'g')
            else c."payment_code"
        end as "payment_code",
        c."order_id" as "order_id",
        c."payment_method_id" as "payment_method_id",
        case
            when btrim(c."status") = '' or btrim(c."status") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(c."status") not in ('pending', 'authorized', 'captured', 'failed', 'refunded', 'cancelled') then c."status"
            else c."status"
        end as "status",
        case
            when btrim(c."amount") = '' or btrim(c."amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."amount", 'R$', ''), ' ', '')) ~ '^-' then c."amount"
            when c."amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."amount", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."amount", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."amount", 'R$', ''), ' ', ''), ',', '') end
            when c."amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."amount"
            else c."amount"
        end as "amount",
        case
            when btrim(c."currency") = '' or btrim(c."currency") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."currency" like '%;%' and (c."installments" is null or btrim(c."installments") = '') and (c."authorized_at" is null or btrim(c."authorized_at") = '') then c."currency"
            when c."currency" ~ '(Ã[-¿]|Â[-¿])' and c."currency" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."currency", 'LATIN1'), 'UTF8')
            when c."currency" <> btrim(c."currency") or c."currency" ~ '  ' then regexp_replace(btrim(c."currency"), '\s+', ' ', 'g')
            else c."currency"
        end as "currency",
        case
            when btrim(c."installments") = '' or btrim(c."installments") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            else c."installments"
        end as "installments",
        case
            when btrim(c."authorized_at") = '' or btrim(c."authorized_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."authorized_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."authorized_at" from 6 for 2)::int between 1 and 12 and substring(c."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 9 for 2)::int > 30) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int > 29) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int = 29 and not (substring(c."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 1 for 4)::int % 400 = 0)))) when c."authorized_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."authorized_at" from 4 for 2)::int between 1 and 12 and substring(c."authorized_at" from 1 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 1 for 2)::int > 30) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int > 29) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int = 29 and not (substring(c."authorized_at" from 7 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 7 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 7 for 4)::int % 400 = 0)))) when c."authorized_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."authorized_at"
            when case when c."authorized_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."authorized_at" from 6 for 2)::int between 1 and 12 and substring(c."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 9 for 2)::int > 30) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int > 29) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int = 29 and not (substring(c."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 1 for 4)::int % 400 = 0)))) then left(c."authorized_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."authorized_at"
            when case when c."authorized_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."authorized_at" from 4 for 2)::int between 1 and 12 and substring(c."authorized_at" from 1 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 1 for 2)::int > 30) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int > 29) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int = 29 and not (substring(c."authorized_at" from 7 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 7 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 7 for 4)::int % 400 = 0)))) when c."authorized_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."authorized_at" from 6 for 2)::int between 1 and 12 and substring(c."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 9 for 2)::int > 30) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int > 29) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int = 29 and not (substring(c."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."authorized_at" ~ '^[0-9]{2}/' then to_date(c."authorized_at", 'DD/MM/YYYY')::text else to_date(c."authorized_at", 'YYYY.MM.DD')::text end
            when c."authorized_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."authorized_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."authorized_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."authorized_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."authorized_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."authorized_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."authorized_at"
            else c."authorized_at"
        end as "authorized_at",
        case
            when btrim(c."captured_at") = '' or btrim(c."captured_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."captured_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."captured_at" from 6 for 2)::int between 1 and 12 and substring(c."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 9 for 2)::int > 30) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int > 29) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int = 29 and not (substring(c."captured_at" from 1 for 4)::int % 4 = 0 and (substring(c."captured_at" from 1 for 4)::int % 100 <> 0 or substring(c."captured_at" from 1 for 4)::int % 400 = 0)))) when c."captured_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."captured_at" from 4 for 2)::int between 1 and 12 and substring(c."captured_at" from 1 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 1 for 2)::int > 30) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int > 29) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int = 29 and not (substring(c."captured_at" from 7 for 4)::int % 4 = 0 and (substring(c."captured_at" from 7 for 4)::int % 100 <> 0 or substring(c."captured_at" from 7 for 4)::int % 400 = 0)))) when c."captured_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."captured_at"
            when case when c."captured_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."captured_at" from 6 for 2)::int between 1 and 12 and substring(c."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 9 for 2)::int > 30) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int > 29) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int = 29 and not (substring(c."captured_at" from 1 for 4)::int % 4 = 0 and (substring(c."captured_at" from 1 for 4)::int % 100 <> 0 or substring(c."captured_at" from 1 for 4)::int % 400 = 0)))) then left(c."captured_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."captured_at"
            when case when c."captured_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."captured_at" from 4 for 2)::int between 1 and 12 and substring(c."captured_at" from 1 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 1 for 2)::int > 30) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int > 29) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int = 29 and not (substring(c."captured_at" from 7 for 4)::int % 4 = 0 and (substring(c."captured_at" from 7 for 4)::int % 100 <> 0 or substring(c."captured_at" from 7 for 4)::int % 400 = 0)))) when c."captured_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."captured_at" from 6 for 2)::int between 1 and 12 and substring(c."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 9 for 2)::int > 30) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int > 29) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int = 29 and not (substring(c."captured_at" from 1 for 4)::int % 4 = 0 and (substring(c."captured_at" from 1 for 4)::int % 100 <> 0 or substring(c."captured_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."captured_at" ~ '^[0-9]{2}/' then to_date(c."captured_at", 'DD/MM/YYYY')::text else to_date(c."captured_at", 'YYYY.MM.DD')::text end
            when c."captured_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."captured_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."captured_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."captured_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."captured_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."captured_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."captured_at"
            else c."captured_at"
        end as "captured_at",
        case
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."created_at" ~ '^[0-9]{2}/' then to_date(c."created_at", 'DD/MM/YYYY')::text else to_date(c."created_at", 'YYYY.MM.DD')::text end
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."created_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."created_at"
            else c."created_at"
        end as "created_at",
        case
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."updated_at" ~ '^[0-9]{2}/' then to_date(c."updated_at", 'DD/MM/YYYY')::text else to_date(c."updated_at", 'YYYY.MM.DD')::text end
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."updated_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."updated_at"
            else c."updated_at"
        end as "updated_at",
        case
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."deleted_at" ~ '^[0-9]{2}/' then to_date(c."deleted_at", 'DD/MM/YYYY')::text else to_date(c."deleted_at", 'YYYY.MM.DD')::text end
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."deleted_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."deleted_at"
            else c."deleted_at"
        end as "deleted_at"
    from captura c

)

select
    c.legacy_row_id,
    c._airbyte_generation_id                    as snapshot_id,
    c._airbyte_extracted_at                     as snapshot_at,
    'legacy'                                    as source_system,

    -- ── Valores tratados ─────────────────────────────────────────────────────
    l."id",
    l."payment_code",
    l."order_id",
    l."payment_method_id",
    l."status",
    l."amount",
    l."currency",
    l."installments",
    l."authorized_at",
    l."captured_at",
    l."created_at",
    l."updated_at",
    l."deleted_at",

    -- ── Achados por coluna, sem os nulos ─────────────────────────────────────
    jsonb_strip_nulls(
        jsonb_build_object(
            'id', case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
        end,
            'payment_code', case
            when btrim(c."payment_code") = '' or btrim(c."payment_code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."payment_code" like '%;%' and (c."order_id" is null or btrim(c."order_id") = '') and (c."payment_method_id" is null or btrim(c."payment_method_id") = '') then 'TEXT_DELIMITER'
            when c."payment_code" ~ '(Ã[-¿]|Â[-¿])' and c."payment_code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."payment_code" <> btrim(c."payment_code") or c."payment_code" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'status', case
            when btrim(l."status") not in ('pending', 'authorized', 'captured', 'failed', 'refunded', 'cancelled') then 'ENUM_UNKNOWN'
            when btrim(c."status") = '' or btrim(c."status") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(c."status") not in ('pending', 'authorized', 'captured', 'failed', 'refunded', 'cancelled') then 'ENUM_UNKNOWN'
        end,
            'amount', case
            when btrim(replace(replace(l."amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when l."amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
            when btrim(c."amount") = '' or btrim(c."amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'currency', case
            when btrim(c."currency") = '' or btrim(c."currency") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."currency" like '%;%' and (c."installments" is null or btrim(c."installments") = '') and (c."authorized_at" is null or btrim(c."authorized_at") = '') then 'TEXT_DELIMITER'
            when c."currency" ~ '(Ã[-¿]|Â[-¿])' and c."currency" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."currency" <> btrim(c."currency") or c."currency" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'installments', case
            when btrim(c."installments") = '' or btrim(c."installments") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
        end,
            'authorized_at', case
            when case when l."authorized_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."authorized_at" from 6 for 2)::int between 1 and 12 and substring(l."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(l."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."authorized_at" from 9 for 2)::int > 30) and not (substring(l."authorized_at" from 6 for 2)::int = 2 and substring(l."authorized_at" from 9 for 2)::int > 29) and not (substring(l."authorized_at" from 6 for 2)::int = 2 and substring(l."authorized_at" from 9 for 2)::int = 29 and not (substring(l."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(l."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(l."authorized_at" from 1 for 4)::int % 400 = 0)))) when l."authorized_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."authorized_at" from 4 for 2)::int between 1 and 12 and substring(l."authorized_at" from 1 for 2)::int between 1 and 31 and not (substring(l."authorized_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."authorized_at" from 1 for 2)::int > 30) and not (substring(l."authorized_at" from 4 for 2)::int = 2 and substring(l."authorized_at" from 1 for 2)::int > 29) and not (substring(l."authorized_at" from 4 for 2)::int = 2 and substring(l."authorized_at" from 1 for 2)::int = 29 and not (substring(l."authorized_at" from 7 for 4)::int % 4 = 0 and (substring(l."authorized_at" from 7 for 4)::int % 100 <> 0 or substring(l."authorized_at" from 7 for 4)::int % 400 = 0)))) when l."authorized_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."authorized_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."authorized_at" from 6 for 2)::int between 1 and 12 and substring(l."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(l."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."authorized_at" from 9 for 2)::int > 30) and not (substring(l."authorized_at" from 6 for 2)::int = 2 and substring(l."authorized_at" from 9 for 2)::int > 29) and not (substring(l."authorized_at" from 6 for 2)::int = 2 and substring(l."authorized_at" from 9 for 2)::int = 29 and not (substring(l."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(l."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(l."authorized_at" from 1 for 4)::int % 400 = 0)))) then left(l."authorized_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."authorized_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."authorized_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."authorized_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."authorized_at") = '' or btrim(c."authorized_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."authorized_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."authorized_at" from 6 for 2)::int between 1 and 12 and substring(c."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 9 for 2)::int > 30) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int > 29) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int = 29 and not (substring(c."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 1 for 4)::int % 400 = 0)))) when c."authorized_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."authorized_at" from 4 for 2)::int between 1 and 12 and substring(c."authorized_at" from 1 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 1 for 2)::int > 30) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int > 29) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int = 29 and not (substring(c."authorized_at" from 7 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 7 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 7 for 4)::int % 400 = 0)))) when c."authorized_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."authorized_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."authorized_at" from 6 for 2)::int between 1 and 12 and substring(c."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 9 for 2)::int > 30) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int > 29) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int = 29 and not (substring(c."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 1 for 4)::int % 400 = 0)))) then left(c."authorized_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."authorized_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."authorized_at" from 4 for 2)::int between 1 and 12 and substring(c."authorized_at" from 1 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 1 for 2)::int > 30) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int > 29) and not (substring(c."authorized_at" from 4 for 2)::int = 2 and substring(c."authorized_at" from 1 for 2)::int = 29 and not (substring(c."authorized_at" from 7 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 7 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 7 for 4)::int % 400 = 0)))) when c."authorized_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."authorized_at" from 6 for 2)::int between 1 and 12 and substring(c."authorized_at" from 9 for 2)::int between 1 and 31 and not (substring(c."authorized_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."authorized_at" from 9 for 2)::int > 30) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int > 29) and not (substring(c."authorized_at" from 6 for 2)::int = 2 and substring(c."authorized_at" from 9 for 2)::int = 29 and not (substring(c."authorized_at" from 1 for 4)::int % 4 = 0 and (substring(c."authorized_at" from 1 for 4)::int % 100 <> 0 or substring(c."authorized_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."authorized_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."authorized_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."authorized_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."authorized_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."authorized_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'captured_at', case
            when case when l."captured_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."captured_at" from 6 for 2)::int between 1 and 12 and substring(l."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(l."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."captured_at" from 9 for 2)::int > 30) and not (substring(l."captured_at" from 6 for 2)::int = 2 and substring(l."captured_at" from 9 for 2)::int > 29) and not (substring(l."captured_at" from 6 for 2)::int = 2 and substring(l."captured_at" from 9 for 2)::int = 29 and not (substring(l."captured_at" from 1 for 4)::int % 4 = 0 and (substring(l."captured_at" from 1 for 4)::int % 100 <> 0 or substring(l."captured_at" from 1 for 4)::int % 400 = 0)))) when l."captured_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."captured_at" from 4 for 2)::int between 1 and 12 and substring(l."captured_at" from 1 for 2)::int between 1 and 31 and not (substring(l."captured_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."captured_at" from 1 for 2)::int > 30) and not (substring(l."captured_at" from 4 for 2)::int = 2 and substring(l."captured_at" from 1 for 2)::int > 29) and not (substring(l."captured_at" from 4 for 2)::int = 2 and substring(l."captured_at" from 1 for 2)::int = 29 and not (substring(l."captured_at" from 7 for 4)::int % 4 = 0 and (substring(l."captured_at" from 7 for 4)::int % 100 <> 0 or substring(l."captured_at" from 7 for 4)::int % 400 = 0)))) when l."captured_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."captured_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."captured_at" from 6 for 2)::int between 1 and 12 and substring(l."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(l."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."captured_at" from 9 for 2)::int > 30) and not (substring(l."captured_at" from 6 for 2)::int = 2 and substring(l."captured_at" from 9 for 2)::int > 29) and not (substring(l."captured_at" from 6 for 2)::int = 2 and substring(l."captured_at" from 9 for 2)::int = 29 and not (substring(l."captured_at" from 1 for 4)::int % 4 = 0 and (substring(l."captured_at" from 1 for 4)::int % 100 <> 0 or substring(l."captured_at" from 1 for 4)::int % 400 = 0)))) then left(l."captured_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."captured_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."captured_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."captured_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."captured_at") = '' or btrim(c."captured_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."captured_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."captured_at" from 6 for 2)::int between 1 and 12 and substring(c."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 9 for 2)::int > 30) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int > 29) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int = 29 and not (substring(c."captured_at" from 1 for 4)::int % 4 = 0 and (substring(c."captured_at" from 1 for 4)::int % 100 <> 0 or substring(c."captured_at" from 1 for 4)::int % 400 = 0)))) when c."captured_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."captured_at" from 4 for 2)::int between 1 and 12 and substring(c."captured_at" from 1 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 1 for 2)::int > 30) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int > 29) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int = 29 and not (substring(c."captured_at" from 7 for 4)::int % 4 = 0 and (substring(c."captured_at" from 7 for 4)::int % 100 <> 0 or substring(c."captured_at" from 7 for 4)::int % 400 = 0)))) when c."captured_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."captured_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."captured_at" from 6 for 2)::int between 1 and 12 and substring(c."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 9 for 2)::int > 30) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int > 29) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int = 29 and not (substring(c."captured_at" from 1 for 4)::int % 4 = 0 and (substring(c."captured_at" from 1 for 4)::int % 100 <> 0 or substring(c."captured_at" from 1 for 4)::int % 400 = 0)))) then left(c."captured_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."captured_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."captured_at" from 4 for 2)::int between 1 and 12 and substring(c."captured_at" from 1 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 1 for 2)::int > 30) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int > 29) and not (substring(c."captured_at" from 4 for 2)::int = 2 and substring(c."captured_at" from 1 for 2)::int = 29 and not (substring(c."captured_at" from 7 for 4)::int % 4 = 0 and (substring(c."captured_at" from 7 for 4)::int % 100 <> 0 or substring(c."captured_at" from 7 for 4)::int % 400 = 0)))) when c."captured_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."captured_at" from 6 for 2)::int between 1 and 12 and substring(c."captured_at" from 9 for 2)::int between 1 and 31 and not (substring(c."captured_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."captured_at" from 9 for 2)::int > 30) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int > 29) and not (substring(c."captured_at" from 6 for 2)::int = 2 and substring(c."captured_at" from 9 for 2)::int = 29 and not (substring(c."captured_at" from 1 for 4)::int % 4 = 0 and (substring(c."captured_at" from 1 for 4)::int % 100 <> 0 or substring(c."captured_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."captured_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."captured_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."captured_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."captured_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."captured_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'created_at', case
            when case when l."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."created_at" from 6 for 2)::int between 1 and 12 and substring(l."created_at" from 9 for 2)::int between 1 and 31 and not (substring(l."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 9 for 2)::int > 30) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int > 29) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int = 29 and not (substring(l."created_at" from 1 for 4)::int % 4 = 0 and (substring(l."created_at" from 1 for 4)::int % 100 <> 0 or substring(l."created_at" from 1 for 4)::int % 400 = 0)))) when l."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."created_at" from 4 for 2)::int between 1 and 12 and substring(l."created_at" from 1 for 2)::int between 1 and 31 and not (substring(l."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 1 for 2)::int > 30) and not (substring(l."created_at" from 4 for 2)::int = 2 and substring(l."created_at" from 1 for 2)::int > 29) and not (substring(l."created_at" from 4 for 2)::int = 2 and substring(l."created_at" from 1 for 2)::int = 29 and not (substring(l."created_at" from 7 for 4)::int % 4 = 0 and (substring(l."created_at" from 7 for 4)::int % 100 <> 0 or substring(l."created_at" from 7 for 4)::int % 400 = 0)))) when l."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."created_at" from 6 for 2)::int between 1 and 12 and substring(l."created_at" from 9 for 2)::int between 1 and 31 and not (substring(l."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 9 for 2)::int > 30) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int > 29) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int = 29 and not (substring(l."created_at" from 1 for 4)::int % 4 = 0 and (substring(l."created_at" from 1 for 4)::int % 100 <> 0 or substring(l."created_at" from 1 for 4)::int % 400 = 0)))) then left(l."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'updated_at', case
            when case when l."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."updated_at" from 6 for 2)::int between 1 and 12 and substring(l."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 9 for 2)::int > 30) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int > 29) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int = 29 and not (substring(l."updated_at" from 1 for 4)::int % 4 = 0 and (substring(l."updated_at" from 1 for 4)::int % 100 <> 0 or substring(l."updated_at" from 1 for 4)::int % 400 = 0)))) when l."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."updated_at" from 4 for 2)::int between 1 and 12 and substring(l."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 1 for 2)::int > 30) and not (substring(l."updated_at" from 4 for 2)::int = 2 and substring(l."updated_at" from 1 for 2)::int > 29) and not (substring(l."updated_at" from 4 for 2)::int = 2 and substring(l."updated_at" from 1 for 2)::int = 29 and not (substring(l."updated_at" from 7 for 4)::int % 4 = 0 and (substring(l."updated_at" from 7 for 4)::int % 100 <> 0 or substring(l."updated_at" from 7 for 4)::int % 400 = 0)))) when l."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."updated_at" from 6 for 2)::int between 1 and 12 and substring(l."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 9 for 2)::int > 30) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int > 29) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int = 29 and not (substring(l."updated_at" from 1 for 4)::int % 4 = 0 and (substring(l."updated_at" from 1 for 4)::int % 100 <> 0 or substring(l."updated_at" from 1 for 4)::int % 400 = 0)))) then left(l."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'deleted_at', case
            when case when l."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."deleted_at" from 6 for 2)::int between 1 and 12 and substring(l."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 9 for 2)::int > 30) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int > 29) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int = 29 and not (substring(l."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 1 for 4)::int % 400 = 0)))) when l."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."deleted_at" from 4 for 2)::int between 1 and 12 and substring(l."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 1 for 2)::int > 30) and not (substring(l."deleted_at" from 4 for 2)::int = 2 and substring(l."deleted_at" from 1 for 2)::int > 29) and not (substring(l."deleted_at" from 4 for 2)::int = 2 and substring(l."deleted_at" from 1 for 2)::int = 29 and not (substring(l."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 7 for 4)::int % 400 = 0)))) when l."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."deleted_at" from 6 for 2)::int between 1 and 12 and substring(l."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 9 for 2)::int > 30) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int > 29) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int = 29 and not (substring(l."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(l."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end
        )
    )                                           as achados,
    jsonb_build_object('id', c."id", 'payment_code', c."payment_code", 'order_id', c."order_id", 'payment_method_id', c."payment_method_id", 'status', c."status", 'amount', c."amount", 'currency', c."currency", 'installments', c."installments", 'authorized_at', c."authorized_at", 'captured_at', c."captured_at", 'created_at', c."created_at", 'updated_at', c."updated_at", 'deleted_at', c."deleted_at")              as original_payload
from captura c
join limpo l on l.legacy_row_id = c.legacy_row_id
