-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  GERADO por `make legacy-models` a partir de src/mvp_ed1/legacy/         ║
-- ║  catalogo.yml. Não edite este arquivo: a próxima geração o sobrescreve.  ║
-- ║  Erro aqui é sintoma — corrija no catálogo ou em `regras.py`.            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- Limpeza de `legacy.price_lists` — camada `staging` (ADR-0016).
--
-- Uma linha por ocorrência física da **captura mais recente**. Reter capturas
-- antigas (ADR-0037) não significa somá-las: o tratamento olha a última, e as
-- anteriores existem para comparação e reprocessamento.
--
-- Duas saídas por coluna: o valor tratado e o **achado**, que é o código da
-- primeira falha que casa. O valor original permanece acessível em
-- `raw_legacy`, que é imutável.

with captura as (

    select *
    from {{ source('legacy', 'price_lists') }}
    where _airbyte_generation_id = coalesce(
        {{ legacy_snapshot_id() }}, (
        select max(_airbyte_generation_id) from {{ source('legacy', 'price_lists') }}
    ))

),

-- A limpeza vem **antes** dos achados, e não junto: o achado de rejeição
-- precisa ser conferido contra o valor já convertido, senão uma conversão
-- bem-sucedida esconde a invalidade do resultado dela.
limpo as (

    select
        c.legacy_row_id,
        case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            else c."id"
        end as "id",
        case
            when btrim(c."code") = '' or btrim(c."code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."code" like '%;%' and (c."name" is null or btrim(c."name") = '') and (c."sales_channel_id" is null or btrim(c."sales_channel_id") = '') then c."code"
            when c."code" ~ '(Ã[-¿]|Â[-¿])' and c."code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."code", 'LATIN1'), 'UTF8')
            when c."code" <> btrim(c."code") or c."code" ~ '  ' then regexp_replace(btrim(c."code"), '\s+', ' ', 'g')
            else c."code"
        end as "code",
        case
            when btrim(c."name") = '' or btrim(c."name") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."name" like '%;%' and (c."sales_channel_id" is null or btrim(c."sales_channel_id") = '') and (c."currency" is null or btrim(c."currency") = '') then c."name"
            when c."name" ~ '(Ã[-¿]|Â[-¿])' and c."name" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."name", 'LATIN1'), 'UTF8')
            when c."name" <> btrim(c."name") or c."name" ~ '  ' then regexp_replace(btrim(c."name"), '\s+', ' ', 'g')
            else c."name"
        end as "name",
        c."sales_channel_id" as "sales_channel_id",
        case
            when btrim(c."currency") = '' or btrim(c."currency") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."currency" like '%;%' and (c."valid_from" is null or btrim(c."valid_from") = '') and (c."valid_to" is null or btrim(c."valid_to") = '') then c."currency"
            when c."currency" ~ '(Ã[-¿]|Â[-¿])' and c."currency" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."currency", 'LATIN1'), 'UTF8')
            when c."currency" <> btrim(c."currency") or c."currency" ~ '  ' then regexp_replace(btrim(c."currency"), '\s+', ' ', 'g')
            else c."currency"
        end as "currency",
        case
            when btrim(c."valid_from") = '' or btrim(c."valid_from") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."valid_from" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."valid_from"
            when case when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) then left(c."valid_from", 10)::date > date '{{ var("as_of_date") }}' else false end then c."valid_from"
            when case when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) else false end then case when c."valid_from" ~ '^[0-9]{2}/' then to_date(c."valid_from", 'DD/MM/YYYY')::text else to_date(c."valid_from", 'YYYY.MM.DD')::text end
            when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_from" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."valid_from"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."valid_from" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_from" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_from" !~ '^[0-9]{2}/[0-9]{4}$' then c."valid_from"
            else c."valid_from"
        end as "valid_from",
        case
            when btrim(c."valid_to") = '' or btrim(c."valid_to") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."valid_to" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."valid_to"
            when case when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) else false end then case when c."valid_to" ~ '^[0-9]{2}/' then to_date(c."valid_to", 'DD/MM/YYYY')::text else to_date(c."valid_to", 'YYYY.MM.DD')::text end
            when c."valid_to" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_to" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."valid_to"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."valid_to" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_to" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_to" !~ '^[0-9]{2}/[0-9]{4}$' then c."valid_to"
            else c."valid_to"
        end as "valid_to",
        case
            when btrim(c."is_active") = '' or btrim(c."is_active") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(c."is_active") not in ('true', 'false') and lower(btrim(c."is_active")) in ('true', 'false', 'sim', 'nao', 'não', 's', 'n', '1', '0', 'y', 'yes', 'no') then case when lower(btrim(c."is_active")) in ('true', 'sim', 's', '1', 'y', 'yes') then 'true' else 'false' end
            else c."is_active"
        end as "is_active",
        case
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."created_at" ~ '^[0-9]{2}/' then to_date(c."created_at", 'DD/MM/YYYY')::text else to_date(c."created_at", 'YYYY.MM.DD')::text end
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."created_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."created_at"
            else c."created_at"
        end as "created_at",
        case
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."updated_at" ~ '^[0-9]{2}/' then to_date(c."updated_at", 'DD/MM/YYYY')::text else to_date(c."updated_at", 'YYYY.MM.DD')::text end
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."updated_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."updated_at"
            else c."updated_at"
        end as "updated_at",
        case
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."deleted_at" ~ '^[0-9]{2}/' then to_date(c."deleted_at", 'DD/MM/YYYY')::text else to_date(c."deleted_at", 'YYYY.MM.DD')::text end
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."deleted_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."deleted_at"
            else c."deleted_at"
        end as "deleted_at"
    from captura c

)

select
    c.legacy_row_id,
    c._airbyte_generation_id                    as snapshot_id,
    c._airbyte_extracted_at                     as snapshot_at,
    'legacy'                                    as source_system,

    -- ── Valores tratados ─────────────────────────────────────────────────────
    l."id",
    l."code",
    l."name",
    l."sales_channel_id",
    l."currency",
    l."valid_from",
    l."valid_to",
    l."is_active",
    l."created_at",
    l."updated_at",
    l."deleted_at",

    -- ── Achados por coluna, sem os nulos ─────────────────────────────────────
    jsonb_strip_nulls(
        jsonb_build_object(
            'id', case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
        end,
            'code', case
            when btrim(c."code") = '' or btrim(c."code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."code" like '%;%' and (c."name" is null or btrim(c."name") = '') and (c."sales_channel_id" is null or btrim(c."sales_channel_id") = '') then 'TEXT_DELIMITER'
            when c."code" ~ '(Ã[-¿]|Â[-¿])' and c."code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."code" <> btrim(c."code") or c."code" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'name', case
            when btrim(c."name") = '' or btrim(c."name") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."name" like '%;%' and (c."sales_channel_id" is null or btrim(c."sales_channel_id") = '') and (c."currency" is null or btrim(c."currency") = '') then 'TEXT_DELIMITER'
            when c."name" ~ '(Ã[-¿]|Â[-¿])' and c."name" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."name" <> btrim(c."name") or c."name" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'currency', case
            when btrim(c."currency") = '' or btrim(c."currency") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."currency" like '%;%' and (c."valid_from" is null or btrim(c."valid_from") = '') and (c."valid_to" is null or btrim(c."valid_to") = '') then 'TEXT_DELIMITER'
            when c."currency" ~ '(Ã[-¿]|Â[-¿])' and c."currency" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."currency" <> btrim(c."currency") or c."currency" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'valid_from', case
            when btrim(c."valid_from") = '' or btrim(c."valid_from") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."valid_from" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) then left(c."valid_from", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_from" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."valid_from" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_from" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_from" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'valid_to', case
            when btrim(c."valid_to") = '' or btrim(c."valid_to") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."valid_to" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."valid_to" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_to" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."valid_to" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_to" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_to" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'is_active', case
            when btrim(c."is_active") = '' or btrim(c."is_active") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(c."is_active") not in ('true', 'false') and lower(btrim(c."is_active")) in ('true', 'false', 'sim', 'nao', 'não', 's', 'n', '1', '0', 'y', 'yes', 'no') then 'BOOL_VARIANT'
        end,
            'created_at', case
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'updated_at', case
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'deleted_at', case
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end
        )
    )                                           as achados,
    jsonb_build_object('id', c."id", 'code', c."code", 'name', c."name", 'sales_channel_id', c."sales_channel_id", 'currency', c."currency", 'valid_from', c."valid_from", 'valid_to', c."valid_to", 'is_active', c."is_active", 'created_at', c."created_at", 'updated_at', c."updated_at", 'deleted_at', c."deleted_at")              as original_payload
from captura c
join limpo l on l.legacy_row_id = c.legacy_row_id
