-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  GERADO por `make legacy-models` a partir de src/mvp_ed1/legacy/         ║
-- ║  catalogo.yml. Não edite este arquivo: a próxima geração o sobrescreve.  ║
-- ║  Erro aqui é sintoma — corrija no catálogo ou em `regras.py`.            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- Limpeza de `legacy.product_prices` — camada `staging` (ADR-0016).
--
-- Uma linha por ocorrência física da **captura mais recente**. Reter capturas
-- antigas (ADR-0037) não significa somá-las: o tratamento olha a última, e as
-- anteriores existem para comparação e reprocessamento.
--
-- Duas saídas por coluna: o valor tratado e o **achado**, que é o código da
-- primeira falha que casa. O valor original permanece acessível em
-- `raw_legacy`, que é imutável.

with captura as (

    select *
    from {{ source('legacy', 'product_prices') }}
    -- A captura é escolhida **uma vez**, em `legacy_selected_capture`, e não
    -- aqui. O máximo por tabela parecia equivalente e não é: uma tabela que
    -- não veio na carga nova cairia para a geração anterior sozinha, e o
    -- modelo serviria linhas velhas sem que nada dissesse isso.
    where _airbyte_generation_id = (
        select snapshot_id from {{ ref('legacy_selected_capture') }}
    )

),

-- A limpeza vem **antes** dos achados, e não junto: o achado de rejeição
-- precisa ser conferido contra o valor já convertido, senão uma conversão
-- bem-sucedida esconde a invalidade do resultado dela.
limpo as (

    select
        c.legacy_row_id,
        case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            else c."id"
        end as "id",
        c."price_list_id" as "price_list_id",
        c."product_variant_id" as "product_variant_id",
        case
            when btrim(c."unit_price") = '' or btrim(c."unit_price") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."unit_price", 'R$', ''), ' ', '')) ~ '^-' then c."unit_price"
            when c."unit_price" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."unit_price" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."unit_price" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."unit_price" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."unit_price" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."unit_price", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."unit_price", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."unit_price", 'R$', ''), ' ', ''), ',', '') end
            when c."unit_price" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."unit_price"
            else c."unit_price"
        end as "unit_price",
        case
            when btrim(c."valid_from") = '' or btrim(c."valid_from") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."valid_from" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."valid_from"
            when case when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) then left(c."valid_from", 10)::date > date '{{ var("as_of_date") }}' else false end then c."valid_from"
            when case when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) else false end then case when c."valid_from" ~ '^[0-9]{2}/' then to_date(c."valid_from", 'DD/MM/YYYY')::text else to_date(c."valid_from", 'YYYY.MM.DD')::text end
            when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_from" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."valid_from"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."valid_from" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_from" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_from" !~ '^[0-9]{2}/[0-9]{4}$' then c."valid_from"
            else c."valid_from"
        end as "valid_from",
        case
            when btrim(c."valid_to") = '' or btrim(c."valid_to") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."valid_to" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."valid_to"
            when case when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) else false end then case when c."valid_to" ~ '^[0-9]{2}/' then to_date(c."valid_to", 'DD/MM/YYYY')::text else to_date(c."valid_to", 'YYYY.MM.DD')::text end
            when c."valid_to" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_to" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."valid_to"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."valid_to" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_to" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_to" !~ '^[0-9]{2}/[0-9]{4}$' then c."valid_to"
            else c."valid_to"
        end as "valid_to",
        case
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."created_at" ~ '^[0-9]{2}/' then to_date(c."created_at", 'DD/MM/YYYY')::text else to_date(c."created_at", 'YYYY.MM.DD')::text end
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."created_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."created_at"
            else c."created_at"
        end as "created_at",
        case
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."updated_at" ~ '^[0-9]{2}/' then to_date(c."updated_at", 'DD/MM/YYYY')::text else to_date(c."updated_at", 'YYYY.MM.DD')::text end
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."updated_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."updated_at"
            else c."updated_at"
        end as "updated_at",
        case
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."deleted_at" ~ '^[0-9]{2}/' then to_date(c."deleted_at", 'DD/MM/YYYY')::text else to_date(c."deleted_at", 'YYYY.MM.DD')::text end
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."deleted_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."deleted_at"
            else c."deleted_at"
        end as "deleted_at"
    from captura c

)

select
    c.legacy_row_id,
    c._airbyte_generation_id                    as snapshot_id,
    c._airbyte_extracted_at                     as snapshot_at,
    'legacy'                                    as source_system,

    -- ── Valores tratados ─────────────────────────────────────────────────────
    l."id",
    l."price_list_id",
    l."product_variant_id",
    l."unit_price",
    l."valid_from",
    l."valid_to",
    l."created_at",
    l."updated_at",
    l."deleted_at",

    -- ── Achados por coluna, sem os nulos ─────────────────────────────────────
    jsonb_strip_nulls(
        jsonb_build_object(
            'id', case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
        end,
            'unit_price', case
            when btrim(replace(replace(l."unit_price", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when l."unit_price" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
            when btrim(c."unit_price") = '' or btrim(c."unit_price") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."unit_price", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."unit_price" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."unit_price" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."unit_price" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."unit_price" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."unit_price" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."unit_price" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'valid_from', case
            when case when l."valid_from" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."valid_from" from 6 for 2)::int between 1 and 12 and substring(l."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(l."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."valid_from" from 9 for 2)::int > 30) and not (substring(l."valid_from" from 6 for 2)::int = 2 and substring(l."valid_from" from 9 for 2)::int > 29) and not (substring(l."valid_from" from 6 for 2)::int = 2 and substring(l."valid_from" from 9 for 2)::int = 29 and not (substring(l."valid_from" from 1 for 4)::int % 4 = 0 and (substring(l."valid_from" from 1 for 4)::int % 100 <> 0 or substring(l."valid_from" from 1 for 4)::int % 400 = 0)))) when l."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."valid_from" from 4 for 2)::int between 1 and 12 and substring(l."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(l."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."valid_from" from 1 for 2)::int > 30) and not (substring(l."valid_from" from 4 for 2)::int = 2 and substring(l."valid_from" from 1 for 2)::int > 29) and not (substring(l."valid_from" from 4 for 2)::int = 2 and substring(l."valid_from" from 1 for 2)::int = 29 and not (substring(l."valid_from" from 7 for 4)::int % 4 = 0 and (substring(l."valid_from" from 7 for 4)::int % 100 <> 0 or substring(l."valid_from" from 7 for 4)::int % 400 = 0)))) when l."valid_from" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."valid_from" from 6 for 2)::int between 1 and 12 and substring(l."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(l."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."valid_from" from 9 for 2)::int > 30) and not (substring(l."valid_from" from 6 for 2)::int = 2 and substring(l."valid_from" from 9 for 2)::int > 29) and not (substring(l."valid_from" from 6 for 2)::int = 2 and substring(l."valid_from" from 9 for 2)::int = 29 and not (substring(l."valid_from" from 1 for 4)::int % 4 = 0 and (substring(l."valid_from" from 1 for 4)::int % 100 <> 0 or substring(l."valid_from" from 1 for 4)::int % 400 = 0)))) then left(l."valid_from", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."valid_from" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."valid_from" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."valid_from" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."valid_from") = '' or btrim(c."valid_from") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."valid_from" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) then left(c."valid_from", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."valid_from" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_from" from 4 for 2)::int between 1 and 12 and substring(c."valid_from" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 1 for 2)::int > 30) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int > 29) and not (substring(c."valid_from" from 4 for 2)::int = 2 and substring(c."valid_from" from 1 for 2)::int = 29 and not (substring(c."valid_from" from 7 for 4)::int % 4 = 0 and (substring(c."valid_from" from 7 for 4)::int % 100 <> 0 or substring(c."valid_from" from 7 for 4)::int % 400 = 0)))) when c."valid_from" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_from" from 6 for 2)::int between 1 and 12 and substring(c."valid_from" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_from" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_from" from 9 for 2)::int > 30) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int > 29) and not (substring(c."valid_from" from 6 for 2)::int = 2 and substring(c."valid_from" from 9 for 2)::int = 29 and not (substring(c."valid_from" from 1 for 4)::int % 4 = 0 and (substring(c."valid_from" from 1 for 4)::int % 100 <> 0 or substring(c."valid_from" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."valid_from" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_from" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."valid_from" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_from" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_from" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'valid_to', case
            when case when l."valid_to" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."valid_to" from 6 for 2)::int between 1 and 12 and substring(l."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(l."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."valid_to" from 9 for 2)::int > 30) and not (substring(l."valid_to" from 6 for 2)::int = 2 and substring(l."valid_to" from 9 for 2)::int > 29) and not (substring(l."valid_to" from 6 for 2)::int = 2 and substring(l."valid_to" from 9 for 2)::int = 29 and not (substring(l."valid_to" from 1 for 4)::int % 4 = 0 and (substring(l."valid_to" from 1 for 4)::int % 100 <> 0 or substring(l."valid_to" from 1 for 4)::int % 400 = 0)))) when l."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."valid_to" from 4 for 2)::int between 1 and 12 and substring(l."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(l."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."valid_to" from 1 for 2)::int > 30) and not (substring(l."valid_to" from 4 for 2)::int = 2 and substring(l."valid_to" from 1 for 2)::int > 29) and not (substring(l."valid_to" from 4 for 2)::int = 2 and substring(l."valid_to" from 1 for 2)::int = 29 and not (substring(l."valid_to" from 7 for 4)::int % 4 = 0 and (substring(l."valid_to" from 7 for 4)::int % 100 <> 0 or substring(l."valid_to" from 7 for 4)::int % 400 = 0)))) when l."valid_to" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when l."valid_to" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."valid_to" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."valid_to" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."valid_to") = '' or btrim(c."valid_to") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."valid_to" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."valid_to" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."valid_to" from 4 for 2)::int between 1 and 12 and substring(c."valid_to" from 1 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 1 for 2)::int > 30) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int > 29) and not (substring(c."valid_to" from 4 for 2)::int = 2 and substring(c."valid_to" from 1 for 2)::int = 29 and not (substring(c."valid_to" from 7 for 4)::int % 4 = 0 and (substring(c."valid_to" from 7 for 4)::int % 100 <> 0 or substring(c."valid_to" from 7 for 4)::int % 400 = 0)))) when c."valid_to" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."valid_to" from 6 for 2)::int between 1 and 12 and substring(c."valid_to" from 9 for 2)::int between 1 and 31 and not (substring(c."valid_to" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."valid_to" from 9 for 2)::int > 30) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int > 29) and not (substring(c."valid_to" from 6 for 2)::int = 2 and substring(c."valid_to" from 9 for 2)::int = 29 and not (substring(c."valid_to" from 1 for 4)::int % 4 = 0 and (substring(c."valid_to" from 1 for 4)::int % 100 <> 0 or substring(c."valid_to" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."valid_to" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."valid_to" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."valid_to" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."valid_to" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."valid_to" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'created_at', case
            when case when l."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."created_at" from 6 for 2)::int between 1 and 12 and substring(l."created_at" from 9 for 2)::int between 1 and 31 and not (substring(l."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 9 for 2)::int > 30) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int > 29) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int = 29 and not (substring(l."created_at" from 1 for 4)::int % 4 = 0 and (substring(l."created_at" from 1 for 4)::int % 100 <> 0 or substring(l."created_at" from 1 for 4)::int % 400 = 0)))) when l."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."created_at" from 4 for 2)::int between 1 and 12 and substring(l."created_at" from 1 for 2)::int between 1 and 31 and not (substring(l."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 1 for 2)::int > 30) and not (substring(l."created_at" from 4 for 2)::int = 2 and substring(l."created_at" from 1 for 2)::int > 29) and not (substring(l."created_at" from 4 for 2)::int = 2 and substring(l."created_at" from 1 for 2)::int = 29 and not (substring(l."created_at" from 7 for 4)::int % 4 = 0 and (substring(l."created_at" from 7 for 4)::int % 100 <> 0 or substring(l."created_at" from 7 for 4)::int % 400 = 0)))) when l."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."created_at" from 6 for 2)::int between 1 and 12 and substring(l."created_at" from 9 for 2)::int between 1 and 31 and not (substring(l."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."created_at" from 9 for 2)::int > 30) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int > 29) and not (substring(l."created_at" from 6 for 2)::int = 2 and substring(l."created_at" from 9 for 2)::int = 29 and not (substring(l."created_at" from 1 for 4)::int % 4 = 0 and (substring(l."created_at" from 1 for 4)::int % 100 <> 0 or substring(l."created_at" from 1 for 4)::int % 400 = 0)))) then left(l."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'updated_at', case
            when case when l."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."updated_at" from 6 for 2)::int between 1 and 12 and substring(l."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 9 for 2)::int > 30) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int > 29) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int = 29 and not (substring(l."updated_at" from 1 for 4)::int % 4 = 0 and (substring(l."updated_at" from 1 for 4)::int % 100 <> 0 or substring(l."updated_at" from 1 for 4)::int % 400 = 0)))) when l."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."updated_at" from 4 for 2)::int between 1 and 12 and substring(l."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 1 for 2)::int > 30) and not (substring(l."updated_at" from 4 for 2)::int = 2 and substring(l."updated_at" from 1 for 2)::int > 29) and not (substring(l."updated_at" from 4 for 2)::int = 2 and substring(l."updated_at" from 1 for 2)::int = 29 and not (substring(l."updated_at" from 7 for 4)::int % 4 = 0 and (substring(l."updated_at" from 7 for 4)::int % 100 <> 0 or substring(l."updated_at" from 7 for 4)::int % 400 = 0)))) when l."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."updated_at" from 6 for 2)::int between 1 and 12 and substring(l."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(l."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."updated_at" from 9 for 2)::int > 30) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int > 29) and not (substring(l."updated_at" from 6 for 2)::int = 2 and substring(l."updated_at" from 9 for 2)::int = 29 and not (substring(l."updated_at" from 1 for 4)::int % 4 = 0 and (substring(l."updated_at" from 1 for 4)::int % 100 <> 0 or substring(l."updated_at" from 1 for 4)::int % 400 = 0)))) then left(l."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'deleted_at', case
            when case when l."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(l."deleted_at" from 6 for 2)::int between 1 and 12 and substring(l."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 9 for 2)::int > 30) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int > 29) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int = 29 and not (substring(l."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 1 for 4)::int % 400 = 0)))) when l."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(l."deleted_at" from 4 for 2)::int between 1 and 12 and substring(l."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 1 for 2)::int > 30) and not (substring(l."deleted_at" from 4 for 2)::int = 2 and substring(l."deleted_at" from 1 for 2)::int > 29) and not (substring(l."deleted_at" from 4 for 2)::int = 2 and substring(l."deleted_at" from 1 for 2)::int = 29 and not (substring(l."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 7 for 4)::int % 400 = 0)))) when l."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when l."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(l."deleted_at" from 6 for 2)::int between 1 and 12 and substring(l."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(l."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(l."deleted_at" from 9 for 2)::int > 30) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int > 29) and not (substring(l."deleted_at" from 6 for 2)::int = 2 and substring(l."deleted_at" from 9 for 2)::int = 29 and not (substring(l."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(l."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(l."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(l."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when l."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and l."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and l."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end
        )
    )                                           as achados,
    jsonb_build_object('id', c."id", 'price_list_id', c."price_list_id", 'product_variant_id', c."product_variant_id", 'unit_price', c."unit_price", 'valid_from', c."valid_from", 'valid_to', c."valid_to", 'created_at', c."created_at", 'updated_at', c."updated_at", 'deleted_at', c."deleted_at")              as original_payload
from captura c
join limpo l on l.legacy_row_id = c.legacy_row_id
