-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  GERADO por `make legacy-models` a partir de src/mvp_ed1/legacy/         ║
-- ║  catalogo.yml. Não edite este arquivo: a próxima geração o sobrescreve.  ║
-- ║  Erro aqui é sintoma — corrija no catálogo ou em `regras.py`.            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- Limpeza de `legacy.shipments` — camada `staging` (ADR-0016).
--
-- Uma linha por ocorrência física da **captura mais recente**. Reter capturas
-- antigas (ADR-0037) não significa somá-las: o tratamento olha a última, e as
-- anteriores existem para comparação e reprocessamento.
--
-- Duas saídas por coluna: o valor tratado e o **achado**, que é o código da
-- primeira falha que casa. O valor original permanece acessível em
-- `raw_legacy`, que é imutável.

with captura as (

    select *
    from {{ source('legacy', 'shipments') }}
    where _airbyte_generation_id = coalesce(
        {{ legacy_snapshot_id() }}, (
        select max(_airbyte_generation_id) from {{ source('legacy', 'shipments') }}
    ))

),

-- A limpeza vem **antes** dos achados, e não junto: o achado de rejeição
-- precisa ser conferido contra o valor já convertido, senão uma conversão
-- bem-sucedida esconde a invalidade do resultado dela.
limpo as (

    select
        c.legacy_row_id,
        case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            else c."id"
        end as "id",
        case
            when btrim(c."shipment_code") = '' or btrim(c."shipment_code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."shipment_code" like '%;%' and (c."order_id" is null or btrim(c."order_id") = '') and (c."carrier_id" is null or btrim(c."carrier_id") = '') then c."shipment_code"
            when c."shipment_code" ~ '(Ã[-¿]|Â[-¿])' and c."shipment_code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."shipment_code", 'LATIN1'), 'UTF8')
            when c."shipment_code" <> btrim(c."shipment_code") or c."shipment_code" ~ '  ' then regexp_replace(btrim(c."shipment_code"), '\s+', ' ', 'g')
            else c."shipment_code"
        end as "shipment_code",
        c."order_id" as "order_id",
        c."carrier_id" as "carrier_id",
        c."warehouse_id" as "warehouse_id",
        case
            when btrim(c."status") = '' or btrim(c."status") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(c."status") not in ('created', 'picking', 'dispatched', 'in_transit', 'delivered', 'returned', 'lost') then c."status"
            else c."status"
        end as "status",
        case
            when btrim(c."tracking_code") = '' or btrim(c."tracking_code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when c."tracking_code" like '%;%' and (c."freight_amount" is null or btrim(c."freight_amount") = '') and (c."shipped_at" is null or btrim(c."shipped_at") = '') then c."tracking_code"
            when c."tracking_code" ~ '(Ã[-¿]|Â[-¿])' and c."tracking_code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then convert_from(convert_to(c."tracking_code", 'LATIN1'), 'UTF8')
            when c."tracking_code" <> btrim(c."tracking_code") or c."tracking_code" ~ '  ' then regexp_replace(btrim(c."tracking_code"), '\s+', ' ', 'g')
            else c."tracking_code"
        end as "tracking_code",
        case
            when btrim(c."freight_amount") = '' or btrim(c."freight_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when btrim(replace(replace(c."freight_amount", 'R$', ''), ' ', '')) ~ '^-' then c."freight_amount"
            when c."freight_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."freight_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."freight_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."freight_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."freight_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then case when btrim(replace(replace(c."freight_amount", 'R$', ''), ' ', '')) ~ ',[0-9]{1,4}$' then replace(replace(replace(replace(c."freight_amount", 'R$', ''), ' ', ''), '.', ''), ',', '.') else replace(replace(replace(c."freight_amount", 'R$', ''), ' ', ''), ',', '') end
            when c."freight_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then c."freight_amount"
            else c."freight_amount"
        end as "freight_amount",
        case
            when btrim(c."shipped_at") = '' or btrim(c."shipped_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."shipped_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."shipped_at" from 6 for 2)::int between 1 and 12 and substring(c."shipped_at" from 9 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 9 for 2)::int > 30) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int > 29) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int = 29 and not (substring(c."shipped_at" from 1 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 1 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 1 for 4)::int % 400 = 0)))) when c."shipped_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."shipped_at" from 4 for 2)::int between 1 and 12 and substring(c."shipped_at" from 1 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 1 for 2)::int > 30) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int > 29) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int = 29 and not (substring(c."shipped_at" from 7 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 7 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 7 for 4)::int % 400 = 0)))) when c."shipped_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."shipped_at"
            when case when c."shipped_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."shipped_at" from 6 for 2)::int between 1 and 12 and substring(c."shipped_at" from 9 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 9 for 2)::int > 30) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int > 29) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int = 29 and not (substring(c."shipped_at" from 1 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 1 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 1 for 4)::int % 400 = 0)))) then left(c."shipped_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."shipped_at"
            when case when c."shipped_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."shipped_at" from 4 for 2)::int between 1 and 12 and substring(c."shipped_at" from 1 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 1 for 2)::int > 30) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int > 29) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int = 29 and not (substring(c."shipped_at" from 7 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 7 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 7 for 4)::int % 400 = 0)))) when c."shipped_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."shipped_at" from 6 for 2)::int between 1 and 12 and substring(c."shipped_at" from 9 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 9 for 2)::int > 30) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int > 29) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int = 29 and not (substring(c."shipped_at" from 1 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 1 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."shipped_at" ~ '^[0-9]{2}/' then to_date(c."shipped_at", 'DD/MM/YYYY')::text else to_date(c."shipped_at", 'YYYY.MM.DD')::text end
            when c."shipped_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."shipped_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."shipped_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."shipped_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."shipped_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."shipped_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."shipped_at"
            else c."shipped_at"
        end as "shipped_at",
        case
            when btrim(c."estimated_delivery_at") = '' or btrim(c."estimated_delivery_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."estimated_delivery_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."estimated_delivery_at" from 6 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 9 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 9 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 1 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 1 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 1 for 4)::int % 400 = 0)))) when c."estimated_delivery_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."estimated_delivery_at" from 4 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 1 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 1 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 7 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 7 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 7 for 4)::int % 400 = 0)))) when c."estimated_delivery_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."estimated_delivery_at"
            when case when c."estimated_delivery_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."estimated_delivery_at" from 4 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 1 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 1 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 7 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 7 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 7 for 4)::int % 400 = 0)))) when c."estimated_delivery_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."estimated_delivery_at" from 6 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 9 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 9 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 1 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 1 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."estimated_delivery_at" ~ '^[0-9]{2}/' then to_date(c."estimated_delivery_at", 'DD/MM/YYYY')::text else to_date(c."estimated_delivery_at", 'YYYY.MM.DD')::text end
            when c."estimated_delivery_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."estimated_delivery_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."estimated_delivery_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."estimated_delivery_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."estimated_delivery_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."estimated_delivery_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."estimated_delivery_at"
            else c."estimated_delivery_at"
        end as "estimated_delivery_at",
        case
            when btrim(c."delivered_at") = '' or btrim(c."delivered_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."delivered_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."delivered_at" from 6 for 2)::int between 1 and 12 and substring(c."delivered_at" from 9 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 9 for 2)::int > 30) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int > 29) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int = 29 and not (substring(c."delivered_at" from 1 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 1 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 1 for 4)::int % 400 = 0)))) when c."delivered_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."delivered_at" from 4 for 2)::int between 1 and 12 and substring(c."delivered_at" from 1 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 1 for 2)::int > 30) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int > 29) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int = 29 and not (substring(c."delivered_at" from 7 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 7 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 7 for 4)::int % 400 = 0)))) when c."delivered_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."delivered_at"
            when case when c."delivered_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."delivered_at" from 6 for 2)::int between 1 and 12 and substring(c."delivered_at" from 9 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 9 for 2)::int > 30) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int > 29) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int = 29 and not (substring(c."delivered_at" from 1 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 1 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 1 for 4)::int % 400 = 0)))) then left(c."delivered_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."delivered_at"
            when case when c."delivered_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."delivered_at" from 4 for 2)::int between 1 and 12 and substring(c."delivered_at" from 1 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 1 for 2)::int > 30) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int > 29) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int = 29 and not (substring(c."delivered_at" from 7 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 7 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 7 for 4)::int % 400 = 0)))) when c."delivered_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."delivered_at" from 6 for 2)::int between 1 and 12 and substring(c."delivered_at" from 9 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 9 for 2)::int > 30) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int > 29) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int = 29 and not (substring(c."delivered_at" from 1 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 1 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."delivered_at" ~ '^[0-9]{2}/' then to_date(c."delivered_at", 'DD/MM/YYYY')::text else to_date(c."delivered_at", 'YYYY.MM.DD')::text end
            when c."delivered_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."delivered_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."delivered_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."delivered_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."delivered_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."delivered_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."delivered_at"
            else c."delivered_at"
        end as "delivered_at",
        case
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."created_at"
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."created_at" ~ '^[0-9]{2}/' then to_date(c."created_at", 'DD/MM/YYYY')::text else to_date(c."created_at", 'YYYY.MM.DD')::text end
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."created_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."created_at"
            else c."created_at"
        end as "created_at",
        case
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."updated_at"
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."updated_at" ~ '^[0-9]{2}/' then to_date(c."updated_at", 'DD/MM/YYYY')::text else to_date(c."updated_at", 'YYYY.MM.DD')::text end
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."updated_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."updated_at"
            else c."updated_at"
        end as "updated_at",
        case
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then null
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then c."deleted_at"
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then case when c."deleted_at" ~ '^[0-9]{2}/' then to_date(c."deleted_at", 'DD/MM/YYYY')::text else to_date(c."deleted_at", 'YYYY.MM.DD')::text end
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then (c."deleted_at"::timestamp at time zone 'America/Sao_Paulo')::text
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then c."deleted_at"
            else c."deleted_at"
        end as "deleted_at"
    from captura c

)

select
    c.legacy_row_id,
    c._airbyte_generation_id                    as snapshot_id,
    c._airbyte_extracted_at                     as snapshot_at,
    'legacy'                                    as source_system,

    -- ── Valores tratados ─────────────────────────────────────────────────────
    l."id",
    l."shipment_code",
    l."order_id",
    l."carrier_id",
    l."warehouse_id",
    l."status",
    l."tracking_code",
    l."freight_amount",
    l."shipped_at",
    l."estimated_delivery_at",
    l."delivered_at",
    l."created_at",
    l."updated_at",
    l."deleted_at",

    -- ── Achados por coluna, sem os nulos ─────────────────────────────────────
    jsonb_strip_nulls(
        jsonb_build_object(
            'id', case
            when btrim(c."id") = '' or btrim(c."id") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
        end,
            'shipment_code', case
            when btrim(c."shipment_code") = '' or btrim(c."shipment_code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."shipment_code" like '%;%' and (c."order_id" is null or btrim(c."order_id") = '') and (c."carrier_id" is null or btrim(c."carrier_id") = '') then 'TEXT_DELIMITER'
            when c."shipment_code" ~ '(Ã[-¿]|Â[-¿])' and c."shipment_code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."shipment_code" <> btrim(c."shipment_code") or c."shipment_code" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'status', case
            when btrim(c."status") = '' or btrim(c."status") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(c."status") not in ('created', 'picking', 'dispatched', 'in_transit', 'delivered', 'returned', 'lost') then 'ENUM_UNKNOWN'
        end,
            'tracking_code', case
            when btrim(c."tracking_code") = '' or btrim(c."tracking_code") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when c."tracking_code" like '%;%' and (c."freight_amount" is null or btrim(c."freight_amount") = '') and (c."shipped_at" is null or btrim(c."shipped_at") = '') then 'TEXT_DELIMITER'
            when c."tracking_code" ~ '(Ã[-¿]|Â[-¿])' and c."tracking_code" !~ '(Ã|Â)[A-ZÁÂÃÉÊÍÓÔÕÚÇ ]' then 'TEXT_ENCODING'
            when c."tracking_code" <> btrim(c."tracking_code") or c."tracking_code" ~ '  ' then 'TEXT_WHITESPACE_CASE'
        end,
            'freight_amount', case
            when btrim(c."freight_amount") = '' or btrim(c."freight_amount") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when btrim(replace(replace(c."freight_amount", 'R$', ''), ' ', '')) ~ '^-' then 'MONEY_NEGATIVE'
            when c."freight_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' and (   c."freight_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(\.[0-9]{3})*,[0-9]{1,4}$'   or c."freight_amount" ~ '^-?(R\$)?\s*[0-9]+,[0-9]{1,4}$'   or c."freight_amount" ~ '^-?(R\$)?\s*[0-9]{1,3}(,[0-9]{3})+(\.[0-9]{1,4})?$'   or c."freight_amount" ~ '^-?(R\$)?\s*[0-9]+(\.[0-9]{1,4})?$') then 'MONEY_LOCALE'
            when c."freight_amount" !~ '^-?[0-9]+(\.[0-9]{1,4})?$' then 'MONEY_AMBIGUOUS'
        end,
            'shipped_at', case
            when btrim(c."shipped_at") = '' or btrim(c."shipped_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."shipped_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."shipped_at" from 6 for 2)::int between 1 and 12 and substring(c."shipped_at" from 9 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 9 for 2)::int > 30) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int > 29) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int = 29 and not (substring(c."shipped_at" from 1 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 1 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 1 for 4)::int % 400 = 0)))) when c."shipped_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."shipped_at" from 4 for 2)::int between 1 and 12 and substring(c."shipped_at" from 1 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 1 for 2)::int > 30) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int > 29) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int = 29 and not (substring(c."shipped_at" from 7 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 7 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 7 for 4)::int % 400 = 0)))) when c."shipped_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."shipped_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."shipped_at" from 6 for 2)::int between 1 and 12 and substring(c."shipped_at" from 9 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 9 for 2)::int > 30) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int > 29) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int = 29 and not (substring(c."shipped_at" from 1 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 1 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 1 for 4)::int % 400 = 0)))) then left(c."shipped_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."shipped_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."shipped_at" from 4 for 2)::int between 1 and 12 and substring(c."shipped_at" from 1 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 1 for 2)::int > 30) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int > 29) and not (substring(c."shipped_at" from 4 for 2)::int = 2 and substring(c."shipped_at" from 1 for 2)::int = 29 and not (substring(c."shipped_at" from 7 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 7 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 7 for 4)::int % 400 = 0)))) when c."shipped_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."shipped_at" from 6 for 2)::int between 1 and 12 and substring(c."shipped_at" from 9 for 2)::int between 1 and 31 and not (substring(c."shipped_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."shipped_at" from 9 for 2)::int > 30) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int > 29) and not (substring(c."shipped_at" from 6 for 2)::int = 2 and substring(c."shipped_at" from 9 for 2)::int = 29 and not (substring(c."shipped_at" from 1 for 4)::int % 4 = 0 and (substring(c."shipped_at" from 1 for 4)::int % 100 <> 0 or substring(c."shipped_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."shipped_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."shipped_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."shipped_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."shipped_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."shipped_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'estimated_delivery_at', case
            when btrim(c."estimated_delivery_at") = '' or btrim(c."estimated_delivery_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."estimated_delivery_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."estimated_delivery_at" from 6 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 9 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 9 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 1 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 1 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 1 for 4)::int % 400 = 0)))) when c."estimated_delivery_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."estimated_delivery_at" from 4 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 1 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 1 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 7 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 7 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 7 for 4)::int % 400 = 0)))) when c."estimated_delivery_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."estimated_delivery_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."estimated_delivery_at" from 4 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 1 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 1 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 4 for 2)::int = 2 and substring(c."estimated_delivery_at" from 1 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 7 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 7 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 7 for 4)::int % 400 = 0)))) when c."estimated_delivery_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."estimated_delivery_at" from 6 for 2)::int between 1 and 12 and substring(c."estimated_delivery_at" from 9 for 2)::int between 1 and 31 and not (substring(c."estimated_delivery_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."estimated_delivery_at" from 9 for 2)::int > 30) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int > 29) and not (substring(c."estimated_delivery_at" from 6 for 2)::int = 2 and substring(c."estimated_delivery_at" from 9 for 2)::int = 29 and not (substring(c."estimated_delivery_at" from 1 for 4)::int % 4 = 0 and (substring(c."estimated_delivery_at" from 1 for 4)::int % 100 <> 0 or substring(c."estimated_delivery_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."estimated_delivery_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."estimated_delivery_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."estimated_delivery_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."estimated_delivery_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."estimated_delivery_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'delivered_at', case
            when btrim(c."delivered_at") = '' or btrim(c."delivered_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."delivered_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."delivered_at" from 6 for 2)::int between 1 and 12 and substring(c."delivered_at" from 9 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 9 for 2)::int > 30) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int > 29) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int = 29 and not (substring(c."delivered_at" from 1 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 1 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 1 for 4)::int % 400 = 0)))) when c."delivered_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."delivered_at" from 4 for 2)::int between 1 and 12 and substring(c."delivered_at" from 1 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 1 for 2)::int > 30) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int > 29) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int = 29 and not (substring(c."delivered_at" from 7 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 7 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 7 for 4)::int % 400 = 0)))) when c."delivered_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."delivered_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."delivered_at" from 6 for 2)::int between 1 and 12 and substring(c."delivered_at" from 9 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 9 for 2)::int > 30) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int > 29) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int = 29 and not (substring(c."delivered_at" from 1 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 1 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 1 for 4)::int % 400 = 0)))) then left(c."delivered_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."delivered_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."delivered_at" from 4 for 2)::int between 1 and 12 and substring(c."delivered_at" from 1 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 1 for 2)::int > 30) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int > 29) and not (substring(c."delivered_at" from 4 for 2)::int = 2 and substring(c."delivered_at" from 1 for 2)::int = 29 and not (substring(c."delivered_at" from 7 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 7 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 7 for 4)::int % 400 = 0)))) when c."delivered_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."delivered_at" from 6 for 2)::int between 1 and 12 and substring(c."delivered_at" from 9 for 2)::int between 1 and 31 and not (substring(c."delivered_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."delivered_at" from 9 for 2)::int > 30) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int > 29) and not (substring(c."delivered_at" from 6 for 2)::int = 2 and substring(c."delivered_at" from 9 for 2)::int = 29 and not (substring(c."delivered_at" from 1 for 4)::int % 4 = 0 and (substring(c."delivered_at" from 1 for 4)::int % 100 <> 0 or substring(c."delivered_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."delivered_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."delivered_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."delivered_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."delivered_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."delivered_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'created_at', case
            when btrim(c."created_at") = '' or btrim(c."created_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."created_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) then left(c."created_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."created_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."created_at" from 4 for 2)::int between 1 and 12 and substring(c."created_at" from 1 for 2)::int between 1 and 31 and not (substring(c."created_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 1 for 2)::int > 30) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int > 29) and not (substring(c."created_at" from 4 for 2)::int = 2 and substring(c."created_at" from 1 for 2)::int = 29 and not (substring(c."created_at" from 7 for 4)::int % 4 = 0 and (substring(c."created_at" from 7 for 4)::int % 100 <> 0 or substring(c."created_at" from 7 for 4)::int % 400 = 0)))) when c."created_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."created_at" from 6 for 2)::int between 1 and 12 and substring(c."created_at" from 9 for 2)::int between 1 and 31 and not (substring(c."created_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."created_at" from 9 for 2)::int > 30) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int > 29) and not (substring(c."created_at" from 6 for 2)::int = 2 and substring(c."created_at" from 9 for 2)::int = 29 and not (substring(c."created_at" from 1 for 4)::int % 4 = 0 and (substring(c."created_at" from 1 for 4)::int % 100 <> 0 or substring(c."created_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."created_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."created_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."created_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."created_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."created_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'updated_at', case
            when btrim(c."updated_at") = '' or btrim(c."updated_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."updated_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) then left(c."updated_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."updated_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."updated_at" from 4 for 2)::int between 1 and 12 and substring(c."updated_at" from 1 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 1 for 2)::int > 30) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int > 29) and not (substring(c."updated_at" from 4 for 2)::int = 2 and substring(c."updated_at" from 1 for 2)::int = 29 and not (substring(c."updated_at" from 7 for 4)::int % 4 = 0 and (substring(c."updated_at" from 7 for 4)::int % 100 <> 0 or substring(c."updated_at" from 7 for 4)::int % 400 = 0)))) when c."updated_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."updated_at" from 6 for 2)::int between 1 and 12 and substring(c."updated_at" from 9 for 2)::int between 1 and 31 and not (substring(c."updated_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."updated_at" from 9 for 2)::int > 30) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int > 29) and not (substring(c."updated_at" from 6 for 2)::int = 2 and substring(c."updated_at" from 9 for 2)::int = 29 and not (substring(c."updated_at" from 1 for 4)::int % 4 = 0 and (substring(c."updated_at" from 1 for 4)::int % 100 <> 0 or substring(c."updated_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."updated_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."updated_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."updated_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."updated_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."updated_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end,
            'deleted_at', case
            when btrim(c."deleted_at") = '' or btrim(c."deleted_at") in ('NULL', 'null', 'N/A', '-', '#N/D', '   ') then 'NULL_DISGUISED'
            when case when c."deleted_at" ~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}'   then not (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then not (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{2}/[0-9]{4}$' then true else false end then 'DATE_IMPOSSIBLE'
            when case when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}' and (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) then left(c."deleted_at", 10)::date > date '{{ var("as_of_date") }}' else false end then 'DATE_FUTURE'
            when case when c."deleted_at" ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'   then (substring(c."deleted_at" from 4 for 2)::int between 1 and 12 and substring(c."deleted_at" from 1 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 4 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 1 for 2)::int > 30) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int > 29) and not (substring(c."deleted_at" from 4 for 2)::int = 2 and substring(c."deleted_at" from 1 for 2)::int = 29 and not (substring(c."deleted_at" from 7 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 7 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 7 for 4)::int % 400 = 0)))) when c."deleted_at" ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'   then (substring(c."deleted_at" from 6 for 2)::int between 1 and 12 and substring(c."deleted_at" from 9 for 2)::int between 1 and 31 and not (substring(c."deleted_at" from 6 for 2)::int in (4, 6, 9, 11) and substring(c."deleted_at" from 9 for 2)::int > 30) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int > 29) and not (substring(c."deleted_at" from 6 for 2)::int = 2 and substring(c."deleted_at" from 9 for 2)::int = 29 and not (substring(c."deleted_at" from 1 for 4)::int % 4 = 0 and (substring(c."deleted_at" from 1 for 4)::int % 100 <> 0 or substring(c."deleted_at" from 1 for 4)::int % 400 = 0)))) else false end then 'DATE_FORMAT_KNOWN'
            when c."deleted_at" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}' and c."deleted_at" !~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' then 'DATE_TZ_MISSING'
            when c."deleted_at" !~ '^[0-9]{4}[-.][0-9]{2}[-.][0-9]{2}' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$' and c."deleted_at" !~ '^[0-9]{2}/[0-9]{4}$' then 'DATE_UNPARSEABLE'
        end
        )
    )                                           as achados,
    jsonb_build_object('id', c."id", 'shipment_code', c."shipment_code", 'order_id', c."order_id", 'carrier_id', c."carrier_id", 'warehouse_id', c."warehouse_id", 'status', c."status", 'tracking_code', c."tracking_code", 'freight_amount', c."freight_amount", 'shipped_at', c."shipped_at", 'estimated_delivery_at', c."estimated_delivery_at", 'delivered_at', c."delivered_at", 'created_at', c."created_at", 'updated_at', c."updated_at", 'deleted_at', c."deleted_at")              as original_payload
from captura c
join limpo l on l.legacy_row_id = c.legacy_row_id
