"""cria o schema oltp com as 40 tabelas transacionais

Revision ID: deae0e5943e0
Revises: 
Create Date: 2026-09-04 05:48:53.800121

O `autogenerate` produz **rascunho**, não migração (ADR-0010): o que ele não
detecta — renomeação, conversão de tipo, mudança de constraint — é escrito à
mão, e o `downgrade` é executado antes de a migração ser considerada pronta.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'deae0e5943e0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # AJUSTE MANUAL — o `autogenerate` não emite a criação do schema, e sem ela
    # nenhuma das 40 tabelas tem onde nascer em banco limpo (ADR-0010, regra 1).
    op.execute(sa.schema.CreateSchema('oltp'))

    # ### commands auto generated by Alembic ###
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('code', name=op.f('uq_brands_code')),
    schema='oltp',
    info={'domain': 'catalogo', 'owner': 'data_custodian', 'description': 'Marcas associadas aos produtos.'}
    )
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('objective', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("objective in ('acquisition', 'retention', 'reactivation', 'clearance')", name=op.f('ck_campaigns_objetivo_valido')),
    sa.CheckConstraint('budget_amount is null or budget_amount >= 0', name=op.f('ck_campaigns_orcamento_nao_negativo')),
    sa.CheckConstraint('valid_to > valid_from', name=op.f('ck_campaigns_vigencia_coerente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('code', name=op.f('uq_campaigns_code')),
    schema='oltp',
    info={'domain': 'marketing', 'owner': 'data_custodian', 'description': 'Campanhas de marketing e seus períodos de vigência.'}
    )
    op.create_table('carriers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('service_level', sa.String(length=16), nullable=False),
    sa.Column('tracking_url_template', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("service_level in ('standard', 'express', 'same_day')", name=op.f('ck_carriers_modalidade_valida')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carriers')),
    sa.UniqueConstraint('code', name=op.f('uq_carriers_code')),
    schema='oltp',
    info={'domain': 'logistica', 'owner': 'data_custodian', 'description': 'Transportadoras sintéticas e suas modalidades.'}
    )
    op.create_table('customer_segments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_segments')),
    sa.UniqueConstraint('code', name=op.f('uq_customer_segments_code')),
    schema='oltp',
    info={'domain': 'clientes', 'owner': 'data_custodian', 'description': 'Segmentos comerciais associáveis ao cadastro do cliente.'}
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('method_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("method_type in ('credit_card', 'debit_card', 'pix', 'boleto', 'wallet', 'voucher')", name=op.f('ck_payment_methods_tipo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods')),
    sa.UniqueConstraint('code', name=op.f('uq_payment_methods_code')),
    schema='oltp',
    info={'domain': 'pagamentos', 'owner': 'data_custodian', 'description': 'Tipos de pagamento aceitos, sem armazenar credenciais.'}
    )
    op.create_table('product_categories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('depth >= 0 and depth <= 3', name=op.f('ck_product_categories_profundidade_valida')),
    sa.CheckConstraint('parent_id is null or parent_id <> id', name=op.f('ck_product_categories_sem_auto_referencia')),
    sa.ForeignKeyConstraint(['parent_id'], ['oltp.product_categories.id'], name=op.f('fk_product_categories_parent_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_product_categories_code')),
    schema='oltp',
    info={'domain': 'catalogo', 'owner': 'data_custodian', 'description': 'Hierarquia de categorias e subcategorias do catálogo.'}
    )
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False, schema='oltp')
    op.create_table('sales_channels',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('channel_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel_type in ('web', 'app', 'store')", name=op.f('ck_sales_channels_tipo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_channels')),
    sa.UniqueConstraint('code', name=op.f('uq_sales_channels_code')),
    schema='oltp',
    info={'domain': 'vendas', 'owner': 'data_custodian', 'description': 'Canais de venda como web, aplicativo e loja física.'}
    )
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('supplier_code', sa.String(length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('document', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=2), server_default='BR', nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('payment_terms_days >= 0', name=op.f('ck_suppliers_prazo_nao_negativo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('document', name=op.f('uq_suppliers_document')),
    sa.UniqueConstraint('supplier_code', name=op.f('uq_suppliers_supplier_code')),
    schema='oltp',
    info={'domain': 'compras', 'owner': 'data_custodian', 'description': 'Cadastro sintético dos fornecedores.'}
    )
    op.create_table('support_agents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('agent_code', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('team', sa.String(length=60), nullable=False),
    sa.Column('hired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_agents')),
    sa.UniqueConstraint('agent_code', name=op.f('uq_support_agents_agent_code')),
    sa.UniqueConstraint('email', name=op.f('uq_support_agents_email')),
    schema='oltp',
    info={'domain': 'atendimento', 'owner': 'data_custodian', 'description': 'Agentes sintéticos e suas equipes de atendimento.'}
    )
    op.create_table('warehouses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='BR', nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('capacity_units is null or capacity_units > 0', name=op.f('ck_warehouses_capacidade_positiva')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code')),
    schema='oltp',
    info={'domain': 'estoque', 'owner': 'data_custodian', 'description': 'Centros de distribuição ou locais de estoque.'}
    )
    op.create_table('coupons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("discount_type <> 'percentage' or discount_value <= 100", name=op.f('ck_coupons_percentual_limitado')),
    sa.CheckConstraint("discount_type in ('percentage', 'fixed')", name=op.f('ck_coupons_tipo_de_desconto_valido')),
    sa.CheckConstraint('discount_value > 0', name=op.f('ck_coupons_desconto_positivo')),
    sa.CheckConstraint('max_redemptions is null or max_redemptions > 0', name=op.f('ck_coupons_limite_positivo')),
    sa.CheckConstraint('valid_to > valid_from', name=op.f('ck_coupons_vigencia_coerente')),
    sa.ForeignKeyConstraint(['campaign_id'], ['oltp.campaigns.id'], name=op.f('fk_coupons_campaign_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name=op.f('uq_coupons_code')),
    schema='oltp',
    info={'domain': 'marketing', 'owner': 'data_custodian', 'description': 'Cupons, regras de desconto e limites de utilização.'}
    )
    op.create_index(op.f('ix_coupons_campaign_id'), 'coupons', ['campaign_id'], unique=False, schema='oltp')
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_code', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('document', sa.String(length=32), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('active', 'inactive', 'blocked', 'pending')", name=op.f('ck_customers_status_valido')),
    sa.ForeignKeyConstraint(['segment_id'], ['oltp.customer_segments.id'], name=op.f('fk_customers_segment_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('customer_code', name=op.f('uq_customers_customer_code')),
    sa.UniqueConstraint('document', name=op.f('uq_customers_document')),
    schema='oltp',
    info={'domain': 'clientes', 'owner': 'data_custodian', 'description': 'Cadastro principal do cliente e estado do relacionamento.'}
    )
    op.create_index('ix_customers_segment_id', 'customers', ['segment_id'], unique=False, schema='oltp')
    op.create_table('price_lists',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sales_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('valid_to is null or valid_to > valid_from', name=op.f('ck_price_lists_vigencia_coerente')),
    sa.ForeignKeyConstraint(['sales_channel_id'], ['oltp.sales_channels.id'], name=op.f('fk_price_lists_sales_channel_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_lists')),
    sa.UniqueConstraint('code', name=op.f('uq_price_lists_code')),
    schema='oltp',
    info={'domain': 'catalogo', 'owner': 'data_custodian', 'description': 'Listas de preço por canal, moeda e período de vigência.'}
    )
    op.create_index(op.f('ix_price_lists_sales_channel_id'), 'price_lists', ['sales_channel_id'], unique=False, schema='oltp')
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_code', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('draft', 'active', 'discontinued')", name=op.f('ck_products_status_valido')),
    sa.ForeignKeyConstraint(['brand_id'], ['oltp.brands.id'], name=op.f('fk_products_brand_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['oltp.product_categories.id'], name=op.f('fk_products_category_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('product_code', name=op.f('uq_products_product_code')),
    schema='oltp',
    info={'domain': 'catalogo', 'owner': 'data_custodian', 'description': 'Produto conceitual vendido pelo marketplace.'}
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False, schema='oltp')
    op.create_table('purchase_orders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('draft', 'placed', 'partially_received', 'received', 'cancelled')", name=op.f('ck_purchase_orders_status_valido')),
    sa.CheckConstraint('expected_at is null or expected_at >= ordered_at', name=op.f('ck_purchase_orders_prazo_coerente')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_purchase_orders_total_nao_negativo')),
    sa.ForeignKeyConstraint(['supplier_id'], ['oltp.suppliers.id'], name=op.f('fk_purchase_orders_supplier_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name=op.f('uq_purchase_orders_po_number')),
    schema='oltp',
    info={'domain': 'compras', 'owner': 'data_custodian', 'description': 'Cabeçalho das ordens de compra enviadas a fornecedores.'}
    )
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False, schema='oltp')
    op.create_table('carts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cart_code', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('sales_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'converted') = (converted_at is not null)", name=op.f('ck_carts_conversao_coerente')),
    sa.CheckConstraint("status in ('open', 'converted', 'abandoned', 'expired')", name=op.f('ck_carts_status_valido')),
    sa.ForeignKeyConstraint(['customer_id'], ['oltp.customers.id'], name=op.f('fk_carts_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_channel_id'], ['oltp.sales_channels.id'], name=op.f('fk_carts_sales_channel_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('cart_code', name=op.f('uq_carts_cart_code')),
    schema='oltp',
    info={'domain': 'vendas', 'owner': 'data_custodian', 'description': 'Carrinhos abertos, convertidos, abandonados ou expirados.'}
    )
    op.create_index(op.f('ix_carts_customer_id'), 'carts', ['customer_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_carts_sales_channel_id'), 'carts', ['sales_channel_id'], unique=False, schema='oltp')
    op.create_index('ix_carts_status_updated_at', 'carts', ['status', 'updated_at'], unique=False, schema='oltp')
    op.create_table('customer_addresses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('address_type', sa.String(length=16), nullable=False),
    sa.Column('street', sa.String(length=160), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('complement', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='BR', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("address_type in ('billing', 'shipping')", name=op.f('ck_customer_addresses_tipo_valido')),
    sa.CheckConstraint('valid_to is null or valid_to > valid_from', name=op.f('ck_customer_addresses_vigencia_coerente')),
    sa.ForeignKeyConstraint(['customer_id'], ['oltp.customers.id'], name=op.f('fk_customer_addresses_customer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_addresses')),
    schema='oltp',
    info={'domain': 'clientes', 'owner': 'data_custodian', 'description': 'Endereços de cobrança e entrega, com vigência e indicação de principal.'}
    )
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False, schema='oltp')
    op.create_index('ix_customer_addresses_principal_unico', 'customer_addresses', ['customer_id', 'address_type'], unique=True, schema='oltp', postgresql_where='is_primary and deleted_at is null')
    op.create_table('customer_contacts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_type', sa.String(length=16), nullable=False),
    sa.Column('contact_value', sa.String(length=160), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("contact_type in ('email', 'phone', 'mobile')", name=op.f('ck_customer_contacts_tipo_valido')),
    sa.ForeignKeyConstraint(['customer_id'], ['oltp.customers.id'], name=op.f('fk_customer_contacts_customer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_contacts')),
    schema='oltp',
    info={'domain': 'clientes', 'owner': 'data_custodian', 'description': 'E-mails e telefones sintéticos associados ao cliente.'}
    )
    op.create_index(op.f('ix_customer_contacts_customer_id'), 'customer_contacts', ['customer_id'], unique=False, schema='oltp')
    op.create_index('ix_customer_contacts_principal_unico', 'customer_contacts', ['customer_id', 'contact_type'], unique=True, schema='oltp', postgresql_where='is_primary and deleted_at is null')
    op.create_table('customer_preferences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='pt-BR', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('newsletter_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consent_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['oltp.customers.id'], name=op.f('fk_customer_preferences_customer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_preferences')),
    sa.UniqueConstraint('customer_id', name=op.f('uq_customer_preferences_customer_id')),
    schema='oltp',
    info={'domain': 'clientes', 'owner': 'data_custodian', 'description': 'Preferências de comunicação, idioma e consentimentos simulados.'}
    )
    op.create_table('goods_receipts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('receipt_number', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending', 'completed', 'rejected')", name=op.f('ck_goods_receipts_status_valido')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['oltp.purchase_orders.id'], name=op.f('fk_goods_receipts_purchase_order_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['oltp.warehouses.id'], name=op.f('fk_goods_receipts_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipts')),
    sa.UniqueConstraint('receipt_number', name=op.f('uq_goods_receipts_receipt_number')),
    schema='oltp',
    info={'domain': 'compras', 'owner': 'data_custodian', 'description': 'Registro do recebimento físico de uma ordem de compra.'}
    )
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_goods_receipts_warehouse_id'), 'goods_receipts', ['warehouse_id'], unique=False, schema='oltp')
    op.create_table('product_variants',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('package', sa.String(length=40), nullable=True),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('weight_grams is null or weight_grams > 0', name=op.f('ck_product_variants_peso_positivo')),
    sa.ForeignKeyConstraint(['product_id'], ['oltp.products.id'], name=op.f('fk_product_variants_product_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('barcode', name=op.f('uq_product_variants_barcode')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku')),
    schema='oltp',
    info={'domain': 'catalogo', 'owner': 'data_custodian', 'description': 'SKUs e variações de tamanho, cor ou embalagem.'}
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False, schema='oltp')
    op.create_table('cart_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_quantidade_positiva')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_cart_items_preco_nao_negativo')),
    sa.ForeignKeyConstraint(['cart_id'], ['oltp.carts.id'], name=op.f('fk_cart_items_cart_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['oltp.product_variants.id'], name=op.f('fk_cart_items_product_variant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    schema='oltp',
    info={'domain': 'vendas', 'owner': 'data_custodian', 'description': 'Produtos e quantidades incluídos nos carrinhos; maior tabela do projeto.'}
    )
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_cart_items_product_variant_id'), 'cart_items', ['product_variant_id'], unique=False, schema='oltp')
    op.create_table('inventory_balances',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_available', sa.Integer(), sa.Computed('quantity_on_hand - quantity_reserved', persisted=True), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_inventory_balances_saldo_nao_negativo')),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name=op.f('ck_inventory_balances_reserva_limitada_ao_saldo')),
    sa.CheckConstraint('quantity_reserved >= 0', name=op.f('ck_inventory_balances_reserva_nao_negativa')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['oltp.product_variants.id'], name=op.f('fk_inventory_balances_product_variant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['oltp.warehouses.id'], name=op.f('fk_inventory_balances_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_balances')),
    sa.UniqueConstraint('warehouse_id', 'product_variant_id', name='uq_saldo_por_armazem_sku'),
    schema='oltp',
    info={'domain': 'estoque', 'owner': 'data_custodian', 'description': 'Saldo atual de cada SKU por armazém.'}
    )
    op.create_index(op.f('ix_inventory_balances_product_variant_id'), 'inventory_balances', ['product_variant_id'], unique=False, schema='oltp')
    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('event_sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('causation_id', sa.Uuid(), nullable=True),
    sa.Column('aggregate_version', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(movement_type in ('purchase_receipt', 'customer_return', 'transfer_in', 'adjustment_in') and quantity_delta > 0) or (movement_type in ('sale_dispatch', 'supplier_return', 'transfer_out', 'adjustment_out') and quantity_delta < 0)", name=op.f('ck_inventory_movements_tipo_coerente_com_sinal')),
    sa.CheckConstraint("source_type in ('purchase', 'sale', 'return', 'transfer', 'adjustment')", name=op.f('ck_inventory_movements_origem_valida')),
    sa.CheckConstraint('aggregate_version > 0', name=op.f('ck_inventory_movements_versao_positiva')),
    sa.CheckConstraint('metadata is null or octet_length(metadata::text) <= 4096', name=op.f('ck_inventory_movements_metadata_limitado')),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_inventory_movements_delta_nao_nulo')),
    sa.CheckConstraint('recorded_at >= occurred_at', name=op.f('ck_inventory_movements_causalidade_temporal')),
    sa.CheckConstraint('schema_version > 0', name=op.f('ck_inventory_movements_versao_de_contrato_positiva')),
    sa.CheckConstraint('unit_cost is null or unit_cost >= 0', name=op.f('ck_inventory_movements_custo_nao_negativo')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['oltp.product_variants.id'], name=op.f('fk_inventory_movements_product_variant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['oltp.warehouses.id'], name=op.f('fk_inventory_movements_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('movement_id', name=op.f('pk_inventory_movements')),
    sa.UniqueConstraint('event_sequence', name=op.f('uq_inventory_movements_event_sequence')),
    sa.UniqueConstraint('idempotency_key', name='uq_movimento_idempotencia'),
    sa.UniqueConstraint('warehouse_id', 'product_variant_id', 'aggregate_version', name='uq_movimento_versao_por_agregado'),
    schema='oltp',
    info={'domain': 'estoque', 'owner': 'data_custodian', 'description': 'Livro append-only de entradas, saídas, ajustes e transferências.'}
    )
    op.create_index('ix_inventory_movements_correlation_id', 'inventory_movements', ['correlation_id'], unique=False, schema='oltp', postgresql_where='correlation_id is not null')
    op.create_index('ix_inventory_movements_leitura_incremental', 'inventory_movements', ['recorded_at', 'event_sequence'], unique=False, schema='oltp')
    op.create_index('ix_inventory_movements_linhagem', 'inventory_movements', ['source_type', 'source_id'], unique=False, schema='oltp')
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('sales_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending', 'paid', 'picking', 'shipped', 'delivered', 'cancelled', 'returned')", name=op.f('ck_orders_status_valido')),
    sa.CheckConstraint('discount_amount <= subtotal_amount', name=op.f('ck_orders_desconto_limitado')),
    sa.CheckConstraint('subtotal_amount >= 0 and discount_amount >= 0 and shipping_amount >= 0 and tax_amount >= 0 and total_amount >= 0', name=op.f('ck_orders_valores_nao_negativos')),
    sa.CheckConstraint('total_amount = subtotal_amount - discount_amount + shipping_amount + tax_amount', name=op.f('ck_orders_total_reconcilia')),
    sa.ForeignKeyConstraint(['cart_id'], ['oltp.carts.id'], name=op.f('fk_orders_cart_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['oltp.customers.id'], name=op.f('fk_orders_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_channel_id'], ['oltp.sales_channels.id'], name=op.f('fk_orders_sales_channel_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('cart_id', name=op.f('uq_orders_cart_id')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number')),
    schema='oltp',
    info={'domain': 'vendas', 'owner': 'data_custodian', 'description': 'Cabeçalho do pedido: cliente, canal, valores e estado atual.'}
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False, schema='oltp')
    op.create_index('ix_orders_placed_at', 'orders', ['placed_at'], unique=False, schema='oltp')
    op.create_index(op.f('ix_orders_sales_channel_id'), 'orders', ['sales_channel_id'], unique=False, schema='oltp')
    op.create_table('product_prices',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('price_list_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_product_prices_preco_nao_negativo')),
    sa.CheckConstraint('valid_to is null or valid_to > valid_from', name=op.f('ck_product_prices_vigencia_coerente')),
    sa.ForeignKeyConstraint(['price_list_id'], ['oltp.price_lists.id'], name=op.f('fk_product_prices_price_list_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['oltp.product_variants.id'], name=op.f('fk_product_prices_product_variant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices')),
    schema='oltp',
    info={'domain': 'catalogo', 'owner': 'data_custodian', 'description': 'Preço de cada SKU em uma lista e intervalo de vigência.'}
    )
    op.create_index(op.f('ix_product_prices_product_variant_id'), 'product_prices', ['product_variant_id'], unique=False, schema='oltp')
    op.create_index('uq_product_prices_lista_variante_vigencia', 'product_prices', ['price_list_id', 'product_variant_id', 'valid_from'], unique=True, schema='oltp')
    op.create_table('purchase_order_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_ordered > 0', name=op.f('ck_purchase_order_items_quantidade_positiva')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_purchase_order_items_custo_nao_negativo')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['oltp.product_variants.id'], name=op.f('fk_purchase_order_items_product_variant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['oltp.purchase_orders.id'], name=op.f('fk_purchase_order_items_purchase_order_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items')),
    schema='oltp',
    info={'domain': 'compras', 'owner': 'data_custodian', 'description': 'Produtos, quantidades e custos solicitados ao fornecedor.'}
    )
    op.create_index(op.f('ix_purchase_order_items_product_variant_id'), 'purchase_order_items', ['product_variant_id'], unique=False, schema='oltp')
    op.create_index('uq_purchase_order_items_ordem_variante', 'purchase_order_items', ['purchase_order_id', 'product_variant_id'], unique=True, schema='oltp')
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('coupon_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_coupon_redemptions_desconto_nao_negativo')),
    sa.ForeignKeyConstraint(['coupon_id'], ['oltp.coupons.id'], name=op.f('fk_coupon_redemptions_coupon_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['oltp.customers.id'], name=op.f('fk_coupon_redemptions_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['oltp.orders.id'], name=op.f('fk_coupon_redemptions_order_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_redemptions')),
    schema='oltp',
    info={'domain': 'marketing', 'owner': 'data_custodian', 'description': 'Uso efetivo de cupons por cliente e pedido.'}
    )
    op.create_index('ix_coupon_redemptions_coupon_id', 'coupon_redemptions', ['coupon_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_coupon_redemptions_customer_id'), 'coupon_redemptions', ['customer_id'], unique=False, schema='oltp')
    op.create_index('uq_coupon_redemptions_pedido', 'coupon_redemptions', ['order_id'], unique=True, schema='oltp')
    op.create_table('goods_receipt_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('goods_receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_goods_receipt_items_quantidade_nao_negativa')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_goods_receipt_items_custo_nao_negativo')),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['oltp.goods_receipts.id'], name=op.f('fk_goods_receipt_items_goods_receipt_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['oltp.purchase_order_items.id'], name=op.f('fk_goods_receipt_items_purchase_order_item_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_items')),
    schema='oltp',
    info={'domain': 'compras', 'owner': 'data_custodian', 'description': 'Quantidades efetivamente recebidas por item da ordem de compra.'}
    )
    op.create_index(op.f('ix_goods_receipt_items_purchase_order_item_id'), 'goods_receipt_items', ['purchase_order_item_id'], unique=False, schema='oltp')
    op.create_index('uq_goods_receipt_items_recebimento_item', 'goods_receipt_items', ['goods_receipt_id', 'purchase_order_item_id'], unique=True, schema='oltp')
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('abs(total_amount - (quantity * unit_price - discount_amount + tax_amount)) <= 0.01', name=op.f('ck_order_items_total_reconcilia')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantidade_positiva')),
    sa.CheckConstraint('unit_price >= 0 and discount_amount >= 0 and tax_amount >= 0', name=op.f('ck_order_items_valores_nao_negativos')),
    sa.ForeignKeyConstraint(['order_id'], ['oltp.orders.id'], name=op.f('fk_order_items_order_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['oltp.product_variants.id'], name=op.f('fk_order_items_product_variant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    schema='oltp',
    info={'domain': 'vendas', 'owner': 'data_custodian', 'description': 'Grão comercial do pedido: um SKU comprado em uma linha.'}
    )
    op.create_index(op.f('ix_order_items_product_variant_id'), 'order_items', ['product_variant_id'], unique=False, schema='oltp')
    op.create_index('uq_order_items_pedido_variante', 'order_items', ['order_id', 'product_variant_id'], unique=True, schema='oltp')
    op.create_table('order_status_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_status is null or from_status in ('pending', 'paid', 'picking', 'shipped', 'delivered', 'cancelled', 'returned')", name=op.f('ck_order_status_history_status_origem_valido')),
    sa.CheckConstraint("to_status in ('pending', 'paid', 'picking', 'shipped', 'delivered', 'cancelled', 'returned')", name=op.f('ck_order_status_history_status_destino_valido')),
    sa.CheckConstraint('from_status is distinct from to_status', name=op.f('ck_order_status_history_transicao_efetiva')),
    sa.ForeignKeyConstraint(['order_id'], ['oltp.orders.id'], name=op.f('fk_order_status_history_order_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history')),
    schema='oltp',
    info={'domain': 'vendas', 'owner': 'data_custodian', 'description': 'Histórico temporal das mudanças de estado do pedido.'}
    )
    op.create_index('ix_order_status_history_order_id_changed_at', 'order_status_history', ['order_id', 'changed_at'], unique=False, schema='oltp')
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('payment_code', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_method_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('installments', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending', 'authorized', 'captured', 'failed', 'refunded', 'cancelled')", name=op.f('ck_payments_status_valido')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_valor_positivo')),
    sa.CheckConstraint('captured_at is null or authorized_at is not null', name=op.f('ck_payments_captura_exige_autorizacao')),
    sa.CheckConstraint('captured_at is null or authorized_at is null or captured_at >= authorized_at', name=op.f('ck_payments_causalidade_temporal')),
    sa.CheckConstraint('installments >= 1', name=op.f('ck_payments_parcelas_validas')),
    sa.ForeignKeyConstraint(['order_id'], ['oltp.orders.id'], name=op.f('fk_payments_order_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['oltp.payment_methods.id'], name=op.f('fk_payments_payment_method_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('payment_code', name=op.f('uq_payments_payment_code')),
    schema='oltp',
    info={'domain': 'pagamentos', 'owner': 'data_custodian', 'description': 'Intenção de pagamento associada ao pedido.'}
    )
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_payments_payment_method_id'), 'payments', ['payment_method_id'], unique=False, schema='oltp')
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('shipment_code', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('carrier_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='created', nullable=False),
    sa.Column('tracking_code', sa.String(length=64), nullable=True),
    sa.Column('freight_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('created', 'picking', 'dispatched', 'in_transit', 'delivered', 'returned', 'lost')", name=op.f('ck_shipments_status_valido')),
    sa.CheckConstraint('delivered_at is null or shipped_at is null or delivered_at >= shipped_at', name=op.f('ck_shipments_causalidade_temporal')),
    sa.CheckConstraint('freight_amount >= 0', name=op.f('ck_shipments_frete_nao_negativo')),
    sa.ForeignKeyConstraint(['carrier_id'], ['oltp.carriers.id'], name=op.f('fk_shipments_carrier_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['oltp.orders.id'], name=op.f('fk_shipments_order_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['oltp.warehouses.id'], name=op.f('fk_shipments_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments')),
    sa.UniqueConstraint('shipment_code', name=op.f('uq_shipments_shipment_code')),
    schema='oltp',
    info={'domain': 'logistica', 'owner': 'data_custodian', 'description': 'Remessas criadas para atender pedidos.'}
    )
    op.create_index(op.f('ix_shipments_carrier_id'), 'shipments', ['carrier_id'], unique=False, schema='oltp')
    op.create_index('ix_shipments_order_id', 'shipments', ['order_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False, schema='oltp')
    op.create_table('stock_reservations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('reservation_code', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('active', 'released', 'expired', 'consumed')", name=op.f('ck_stock_reservations_status_valido')),
    sa.CheckConstraint('num_nonnulls(cart_id, order_id) = 1', name=op.f('ck_stock_reservations_origem_unica')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_reservations_quantidade_positiva')),
    sa.ForeignKeyConstraint(['cart_id'], ['oltp.carts.id'], name=op.f('fk_stock_reservations_cart_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['oltp.orders.id'], name=op.f('fk_stock_reservations_order_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['oltp.product_variants.id'], name=op.f('fk_stock_reservations_product_variant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['oltp.warehouses.id'], name=op.f('fk_stock_reservations_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_reservations')),
    sa.UniqueConstraint('reservation_code', name=op.f('uq_stock_reservations_reservation_code')),
    schema='oltp',
    info={'domain': 'estoque', 'owner': 'data_custodian', 'description': 'Reserva de quantidade para carrinhos ou pedidos.'}
    )
    op.create_index('ix_stock_reservations_ativas', 'stock_reservations', ['expires_at'], unique=False, schema='oltp', postgresql_where="status = 'active'")
    op.create_index(op.f('ix_stock_reservations_cart_id'), 'stock_reservations', ['cart_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_stock_reservations_order_id'), 'stock_reservations', ['order_id'], unique=False, schema='oltp')
    op.create_index('ix_stock_reservations_saldo', 'stock_reservations', ['warehouse_id', 'product_variant_id'], unique=False, schema='oltp')
    op.create_table('delivery_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type in ('picked_up', 'in_transit', 'out_for_delivery', 'delivery_attempt', 'delivered', 'returned')", name=op.f('ck_delivery_events_tipo_valido')),
    sa.ForeignKeyConstraint(['shipment_id'], ['oltp.shipments.id'], name=op.f('fk_delivery_events_shipment_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_events')),
    schema='oltp',
    info={'domain': 'logistica', 'owner': 'data_custodian', 'description': 'Eventos de coleta, trânsito, tentativa e entrega.'}
    )
    op.create_index('ix_delivery_events_shipment_id_occurred_at', 'delivery_events', ['shipment_id', 'occurred_at'], unique=False, schema='oltp')
    op.create_table('payment_transactions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('transaction_code', sa.String(length=40), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gateway_response_code', sa.String(length=32), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result in ('succeeded', 'failed', 'pending')", name=op.f('ck_payment_transactions_resultado_valido')),
    sa.CheckConstraint("transaction_type in ('authorization', 'capture', 'void', 'refund')", name=op.f('ck_payment_transactions_tipo_valido')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_transactions_valor_positivo')),
    sa.ForeignKeyConstraint(['payment_id'], ['oltp.payments.id'], name=op.f('fk_payment_transactions_payment_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions')),
    sa.UniqueConstraint('transaction_code', name=op.f('uq_payment_transactions_transaction_code')),
    schema='oltp',
    info={'domain': 'pagamentos', 'owner': 'data_custodian', 'description': 'Tentativas, autorizações, capturas e falhas do pagamento.'}
    )
    op.create_index('ix_payment_transactions_payment_id_occurred_at', 'payment_transactions', ['payment_id', 'occurred_at'], unique=False, schema='oltp')
    op.create_table('shipment_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_shipment_items_quantidade_positiva')),
    sa.ForeignKeyConstraint(['order_item_id'], ['oltp.order_items.id'], name=op.f('fk_shipment_items_order_item_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['oltp.shipments.id'], name=op.f('fk_shipment_items_shipment_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_items')),
    schema='oltp',
    info={'domain': 'logistica', 'owner': 'data_custodian', 'description': 'Quantidades de itens de pedido incluídas em cada remessa.'}
    )
    op.create_index(op.f('ix_shipment_items_order_item_id'), 'shipment_items', ['order_item_id'], unique=False, schema='oltp')
    op.create_index('uq_shipment_items_remessa_item', 'shipment_items', ['shipment_id', 'order_item_id'], unique=True, schema='oltp')
    op.create_table('support_tickets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category in ('delivery', 'payment', 'product', 'return', 'account', 'other')", name=op.f('ck_support_tickets_categoria_valida')),
    sa.CheckConstraint("priority in ('low', 'normal', 'high', 'urgent')", name=op.f('ck_support_tickets_prioridade_valida')),
    sa.CheckConstraint("status in ('open', 'in_progress', 'waiting_customer', 'resolved', 'closed')", name=op.f('ck_support_tickets_status_valido')),
    sa.CheckConstraint('closed_at is null or closed_at >= opened_at', name=op.f('ck_support_tickets_causalidade_temporal')),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['oltp.support_agents.id'], name=op.f('fk_support_tickets_assigned_agent_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['oltp.customers.id'], name=op.f('fk_support_tickets_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['oltp.orders.id'], name=op.f('fk_support_tickets_order_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['oltp.shipments.id'], name=op.f('fk_support_tickets_shipment_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets')),
    sa.UniqueConstraint('ticket_number', name=op.f('uq_support_tickets_ticket_number')),
    schema='oltp',
    info={'domain': 'atendimento', 'owner': 'data_custodian', 'description': 'Solicitações associadas a clientes, pedidos ou entregas.'}
    )
    op.create_index(op.f('ix_support_tickets_assigned_agent_id'), 'support_tickets', ['assigned_agent_id'], unique=False, schema='oltp')
    op.create_index('ix_support_tickets_customer_id', 'support_tickets', ['customer_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_support_tickets_order_id'), 'support_tickets', ['order_id'], unique=False, schema='oltp')
    op.create_index(op.f('ix_support_tickets_shipment_id'), 'support_tickets', ['shipment_id'], unique=False, schema='oltp')
    op.create_index('ix_support_tickets_status_opened_at', 'support_tickets', ['status', 'opened_at'], unique=False, schema='oltp')
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('refund_code', sa.String(length=40), nullable=False),
    sa.Column('payment_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='requested', nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('requested', 'completed', 'rejected')", name=op.f('ck_refunds_status_valido')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_refunds_valor_positivo')),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['oltp.payment_transactions.id'], name=op.f('fk_refunds_payment_transaction_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('refund_code', name=op.f('uq_refunds_refund_code')),
    schema='oltp',
    info={'domain': 'pagamentos', 'owner': 'data_custodian', 'description': 'Reembolsos totais ou parciais de transações capturadas.'}
    )
    op.create_index('ix_refunds_payment_transaction_id', 'refunds', ['payment_transaction_id'], unique=False, schema='oltp')
    op.create_table('ticket_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type in ('created', 'assigned', 'message', 'status_changed', 'resolved', 'reopened')", name=op.f('ck_ticket_events_tipo_valido')),
    sa.ForeignKeyConstraint(['agent_id'], ['oltp.support_agents.id'], name=op.f('fk_ticket_events_agent_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['oltp.support_tickets.id'], name=op.f('fk_ticket_events_ticket_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_events')),
    schema='oltp',
    info={'domain': 'atendimento', 'owner': 'data_custodian', 'description': 'Interações, atribuições e mudanças de estado do chamado.'}
    )
    op.create_index(op.f('ix_ticket_events_agent_id'), 'ticket_events', ['agent_id'], unique=False, schema='oltp')
    op.create_index('ix_ticket_events_ticket_id_occurred_at', 'ticket_events', ['ticket_id', 'occurred_at'], unique=False, schema='oltp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_events_ticket_id_occurred_at', table_name='ticket_events', schema='oltp')
    op.drop_index(op.f('ix_ticket_events_agent_id'), table_name='ticket_events', schema='oltp')
    op.drop_table('ticket_events', schema='oltp')
    op.drop_index('ix_refunds_payment_transaction_id', table_name='refunds', schema='oltp')
    op.drop_table('refunds', schema='oltp')
    op.drop_index('ix_support_tickets_status_opened_at', table_name='support_tickets', schema='oltp')
    op.drop_index(op.f('ix_support_tickets_shipment_id'), table_name='support_tickets', schema='oltp')
    op.drop_index(op.f('ix_support_tickets_order_id'), table_name='support_tickets', schema='oltp')
    op.drop_index('ix_support_tickets_customer_id', table_name='support_tickets', schema='oltp')
    op.drop_index(op.f('ix_support_tickets_assigned_agent_id'), table_name='support_tickets', schema='oltp')
    op.drop_table('support_tickets', schema='oltp')
    op.drop_index('uq_shipment_items_remessa_item', table_name='shipment_items', schema='oltp')
    op.drop_index(op.f('ix_shipment_items_order_item_id'), table_name='shipment_items', schema='oltp')
    op.drop_table('shipment_items', schema='oltp')
    op.drop_index('ix_payment_transactions_payment_id_occurred_at', table_name='payment_transactions', schema='oltp')
    op.drop_table('payment_transactions', schema='oltp')
    op.drop_index('ix_delivery_events_shipment_id_occurred_at', table_name='delivery_events', schema='oltp')
    op.drop_table('delivery_events', schema='oltp')
    op.drop_index('ix_stock_reservations_saldo', table_name='stock_reservations', schema='oltp')
    op.drop_index(op.f('ix_stock_reservations_order_id'), table_name='stock_reservations', schema='oltp')
    op.drop_index(op.f('ix_stock_reservations_cart_id'), table_name='stock_reservations', schema='oltp')
    op.drop_index('ix_stock_reservations_ativas', table_name='stock_reservations', schema='oltp', postgresql_where="status = 'active'")
    op.drop_table('stock_reservations', schema='oltp')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments', schema='oltp')
    op.drop_index('ix_shipments_order_id', table_name='shipments', schema='oltp')
    op.drop_index(op.f('ix_shipments_carrier_id'), table_name='shipments', schema='oltp')
    op.drop_table('shipments', schema='oltp')
    op.drop_index(op.f('ix_payments_payment_method_id'), table_name='payments', schema='oltp')
    op.drop_index('ix_payments_order_id', table_name='payments', schema='oltp')
    op.drop_table('payments', schema='oltp')
    op.drop_index('ix_order_status_history_order_id_changed_at', table_name='order_status_history', schema='oltp')
    op.drop_table('order_status_history', schema='oltp')
    op.drop_index('uq_order_items_pedido_variante', table_name='order_items', schema='oltp')
    op.drop_index(op.f('ix_order_items_product_variant_id'), table_name='order_items', schema='oltp')
    op.drop_table('order_items', schema='oltp')
    op.drop_index('uq_goods_receipt_items_recebimento_item', table_name='goods_receipt_items', schema='oltp')
    op.drop_index(op.f('ix_goods_receipt_items_purchase_order_item_id'), table_name='goods_receipt_items', schema='oltp')
    op.drop_table('goods_receipt_items', schema='oltp')
    op.drop_index('uq_coupon_redemptions_pedido', table_name='coupon_redemptions', schema='oltp')
    op.drop_index(op.f('ix_coupon_redemptions_customer_id'), table_name='coupon_redemptions', schema='oltp')
    op.drop_index('ix_coupon_redemptions_coupon_id', table_name='coupon_redemptions', schema='oltp')
    op.drop_table('coupon_redemptions', schema='oltp')
    op.drop_index('uq_purchase_order_items_ordem_variante', table_name='purchase_order_items', schema='oltp')
    op.drop_index(op.f('ix_purchase_order_items_product_variant_id'), table_name='purchase_order_items', schema='oltp')
    op.drop_table('purchase_order_items', schema='oltp')
    op.drop_index('uq_product_prices_lista_variante_vigencia', table_name='product_prices', schema='oltp')
    op.drop_index(op.f('ix_product_prices_product_variant_id'), table_name='product_prices', schema='oltp')
    op.drop_table('product_prices', schema='oltp')
    op.drop_index(op.f('ix_orders_sales_channel_id'), table_name='orders', schema='oltp')
    op.drop_index('ix_orders_placed_at', table_name='orders', schema='oltp')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders', schema='oltp')
    op.drop_table('orders', schema='oltp')
    op.drop_index('ix_inventory_movements_linhagem', table_name='inventory_movements', schema='oltp')
    op.drop_index('ix_inventory_movements_leitura_incremental', table_name='inventory_movements', schema='oltp')
    op.drop_index('ix_inventory_movements_correlation_id', table_name='inventory_movements', schema='oltp', postgresql_where='correlation_id is not null')
    op.drop_table('inventory_movements', schema='oltp')
    op.drop_index(op.f('ix_inventory_balances_product_variant_id'), table_name='inventory_balances', schema='oltp')
    op.drop_table('inventory_balances', schema='oltp')
    op.drop_index(op.f('ix_cart_items_product_variant_id'), table_name='cart_items', schema='oltp')
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items', schema='oltp')
    op.drop_table('cart_items', schema='oltp')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants', schema='oltp')
    op.drop_table('product_variants', schema='oltp')
    op.drop_index(op.f('ix_goods_receipts_warehouse_id'), table_name='goods_receipts', schema='oltp')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts', schema='oltp')
    op.drop_table('goods_receipts', schema='oltp')
    op.drop_table('customer_preferences', schema='oltp')
    op.drop_index('ix_customer_contacts_principal_unico', table_name='customer_contacts', schema='oltp', postgresql_where='is_primary and deleted_at is null')
    op.drop_index(op.f('ix_customer_contacts_customer_id'), table_name='customer_contacts', schema='oltp')
    op.drop_table('customer_contacts', schema='oltp')
    op.drop_index('ix_customer_addresses_principal_unico', table_name='customer_addresses', schema='oltp', postgresql_where='is_primary and deleted_at is null')
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses', schema='oltp')
    op.drop_table('customer_addresses', schema='oltp')
    op.drop_index('ix_carts_status_updated_at', table_name='carts', schema='oltp')
    op.drop_index(op.f('ix_carts_sales_channel_id'), table_name='carts', schema='oltp')
    op.drop_index(op.f('ix_carts_customer_id'), table_name='carts', schema='oltp')
    op.drop_table('carts', schema='oltp')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders', schema='oltp')
    op.drop_table('purchase_orders', schema='oltp')
    op.drop_index(op.f('ix_products_category_id'), table_name='products', schema='oltp')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products', schema='oltp')
    op.drop_table('products', schema='oltp')
    op.drop_index(op.f('ix_price_lists_sales_channel_id'), table_name='price_lists', schema='oltp')
    op.drop_table('price_lists', schema='oltp')
    op.drop_index('ix_customers_segment_id', table_name='customers', schema='oltp')
    op.drop_table('customers', schema='oltp')
    op.drop_index(op.f('ix_coupons_campaign_id'), table_name='coupons', schema='oltp')
    op.drop_table('coupons', schema='oltp')
    op.drop_table('warehouses', schema='oltp')
    op.drop_table('support_agents', schema='oltp')
    op.drop_table('suppliers', schema='oltp')
    op.drop_table('sales_channels', schema='oltp')
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories', schema='oltp')
    op.drop_table('product_categories', schema='oltp')
    op.drop_table('payment_methods', schema='oltp')
    op.drop_table('customer_segments', schema='oltp')
    op.drop_table('carriers', schema='oltp')
    op.drop_table('campaigns', schema='oltp')
    op.drop_table('brands', schema='oltp')
    # ### end Alembic commands ###

    # AJUSTE MANUAL — simétrico da subida: o schema sai depois das tabelas.
    op.execute(sa.schema.DropSchema('oltp'))
