#!/usr/bin/env bash
# O contador de jobs do Airbyte, lido e avançado por dentro — o passo
# operacional de D50 (plano da Etapa 12, §6).
#
# `snapshot_id` é o `jobId` do Airbyte (ADR-0044). Uma instalação nova recomeça
# em 1, e o armazém restaurado certifica capturas até `max(snapshot_id)`: o
# próximo job nasceria com identidade já usada. A guarda (`identidade.exigir`)
# recusa — e este script é o que faz a sequência interna passar do retido, para
# que o próximo job nasça acima dele.
#
# **Tudo aqui é premissa sobre o interno da ferramenta**, e cada uma é conferida
# antes de agir — a premissa que falhar **para** com a mensagem, e a guarda
# continua protegendo:
#
# - o nó do cluster `kind` é o contêiner `airbyte-abctl-control-plane`, e o
#   banco interno é o pod `airbyte-db-0` do namespace `airbyte-abctl` (nomes do
#   `abctl`, medidos em 21/09/2026 no Airbyte 2.2.0);
# - a tabela é `jobs`, e `jobs.id` é `bigint generated by default as identity`
#   — a sequência sai de `pg_get_serial_sequence('jobs','id')`, e não de um nome
#   escrito aqui (`public.jobs_id_seq`, na versão medida);
# - `setval(seq, N)` faz o **próximo** `nextval` devolver `N + 1`.
#
# Uso:
#   airbyte_jobs.sh ler              maior_job=… ultimo_valor=… chamado=t|f sequencia=…
#   airbyte_jobs.sh avancar <N>      setval para N e relê
#
# Só `avancar` escreve, e só na sequência: nenhum job é criado, nenhuma linha
# de `jobs` é tocada. A listagem da API não muda até um job existir.
set -uo pipefail

NO="${AIRBYTE_ABCTL_NO:-airbyte-abctl-control-plane}"
NAMESPACE="${AIRBYTE_ABCTL_NAMESPACE:-airbyte-abctl}"
POD="${AIRBYTE_DB_POD:-airbyte-db-0}"
BANCO="${AIRBYTE_DB_NAME:-db-airbyte}"
USUARIO="${AIRBYTE_DB_USER:-airbyte}"
PRAZO="${AIRBYTE_DB_PRAZO:-30}"

_psql() {  # $1 = SQL; uma consulta, um resultado sem moldura
	timeout "$PRAZO" docker exec "$NO" kubectl exec -n "$NAMESPACE" "$POD" -- \
		psql -U "$USUARIO" -d "$BANCO" -Atc "$1" 2>&1
}

_falhar() { echo "airbyte_jobs.sh: $*" >&2; exit 3; }

# Cada premissa, conferida em ordem; a primeira que falha explica qual foi.
_sequencia() {
	local tabela seq
	tabela=$(_psql "select to_regclass('jobs')") \
		|| _falhar "não consegui consultar o banco interno do Airbyte ($NO → $NAMESPACE/$POD, $BANCO): $tabela"
	[ -n "$tabela" ] && [ "$tabela" != "" ] || _falhar "premissa falhou: a tabela 'jobs' não existe no banco interno"
	seq=$(_psql "select pg_get_serial_sequence('jobs','id')") \
		|| _falhar "não consegui ler a sequência de jobs.id: $seq"
	[ -n "$seq" ] || _falhar "premissa falhou: 'jobs.id' não tem sequência associada nesta versão do Airbyte"
	printf '%s' "$seq"
}

ler() {
	local seq linha
	seq=$(_sequencia) || exit $?
	linha=$(_psql "select coalesce(max(id), 0), s.last_value, s.is_called from jobs, $seq s group by s.last_value, s.is_called") \
		|| _falhar "não consegui ler jobs e $seq: $linha"
	# `jobs` vazia não devolve linha no join: lê a sequência sozinha.
	[ -n "$linha" ] || linha="0|$(_psql "select last_value, is_called from $seq")"
	IFS='|' read -r maior ultimo chamado <<<"$linha"
	case "$maior$ultimo$chamado" in *[!0-9tf]*|"") _falhar "resposta ilegível do banco interno: '$linha'" ;; esac
	echo "maior_job=$maior ultimo_valor=$ultimo chamado=$chamado sequencia=$seq"
}

avancar() {
	local valor="${1:?uso: airbyte_jobs.sh avancar <N>}" seq resposta
	case "$valor" in ''|*[!0-9]*) _falhar "valor inválido para avançar: '$valor'" ;; esac
	seq=$(_sequencia) || exit $?
	resposta=$(_psql "select setval('$seq', $valor)") || _falhar "setval falhou: $resposta"
	[ "$resposta" = "$valor" ] || _falhar "setval devolveu '$resposta', esperava $valor"
	ler
}

acao="${1:?uso: airbyte_jobs.sh <ler|avancar N>}"; shift
case "$acao" in
ler)     ler ;;
avancar) avancar "$@" ;;
*) echo "airbyte_jobs.sh: ação desconhecida '$acao'" >&2; exit 2 ;;
esac
