"""cria o schema legacy com as 40 tabelas frouxas

Revision ID: f558a05ce90e
Revises: 
Create Date: 2026-09-14 21:55:08.534868

O `autogenerate` produz **rascunho**, não migração (ADR-0010): o que ele não
detecta — renomeação, conversão de tipo, mudança de constraint — é escrito à
mão, e o `downgrade` é executado antes de a migração ser considerada pronta.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f558a05ce90e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # AJUSTE MANUAL — o `autogenerate` não emite a criação do schema, e sem ela
    # nenhuma das 40 tabelas tem onde nascer em banco limpo (ADR-0010, regra 1).
    # Tudo é `text` de propósito, e não há CHECK, NOT NULL, unicidade nem FK:
    # é o que permite ao defeito entrar (Origem Legada §2). A única exceção é
    # `legacy_row_id`, a identidade física da ocorrência (ADR-0038).
    op.execute(sa.schema.CreateSchema('legacy'))

    # ### commands auto generated by Alembic ###
    op.create_table('brands',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('campaigns',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Text(), nullable=True),
    sa.Column('valid_to', sa.Text(), nullable=True),
    sa.Column('budget_amount', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('carriers',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('service_level', sa.Text(), nullable=True),
    sa.Column('tracking_url_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('cart_items',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('cart_id', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Text(), nullable=True),
    sa.Column('added_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('carts',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('cart_code', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('sales_channel_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('converted_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('coupon_redemptions',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('coupon_id', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Text(), nullable=True),
    sa.Column('redeemed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('coupons',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Text(), nullable=True),
    sa.Column('discount_value', sa.Text(), nullable=True),
    sa.Column('min_order_amount', sa.Text(), nullable=True),
    sa.Column('max_redemptions', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Text(), nullable=True),
    sa.Column('valid_to', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('customer_addresses',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('address_type', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('number', sa.Text(), nullable=True),
    sa.Column('complement', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Text(), nullable=True),
    sa.Column('valid_to', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('customer_contacts',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('contact_type', sa.Text(), nullable=True),
    sa.Column('contact_value', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('customer_preferences',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('marketing_opt_in', sa.Text(), nullable=True),
    sa.Column('newsletter_opt_in', sa.Text(), nullable=True),
    sa.Column('consent_updated_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('customer_segments',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('customers',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('customer_code', sa.Text(), nullable=True),
    sa.Column('segment_id', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('delivery_events',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('shipment_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('goods_receipt_items',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('goods_receipt_id', sa.Text(), nullable=True),
    sa.Column('purchase_order_item_id', sa.Text(), nullable=True),
    sa.Column('quantity_received', sa.Text(), nullable=True),
    sa.Column('unit_cost', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('goods_receipts',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('receipt_number', sa.Text(), nullable=True),
    sa.Column('purchase_order_id', sa.Text(), nullable=True),
    sa.Column('warehouse_id', sa.Text(), nullable=True),
    sa.Column('received_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('inventory_balances',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('warehouse_id', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Text(), nullable=True),
    sa.Column('quantity_on_hand', sa.Text(), nullable=True),
    sa.Column('quantity_reserved', sa.Text(), nullable=True),
    sa.Column('last_movement_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('inventory_movements',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('movement_id', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('warehouse_id', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Text(), nullable=True),
    sa.Column('movement_type', sa.Text(), nullable=True),
    sa.Column('quantity_delta', sa.Text(), nullable=True),
    sa.Column('unit_cost', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('causation_id', sa.Text(), nullable=True),
    sa.Column('aggregate_version', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('order_items',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Text(), nullable=True),
    sa.Column('tax_amount', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('order_status_history',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('orders',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('order_number', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('sales_channel_id', sa.Text(), nullable=True),
    sa.Column('cart_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('subtotal_amount', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Text(), nullable=True),
    sa.Column('shipping_amount', sa.Text(), nullable=True),
    sa.Column('tax_amount', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('payment_methods',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('method_type', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('payment_transactions',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('transaction_code', sa.Text(), nullable=True),
    sa.Column('payment_id', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('gateway_response_code', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('payments',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('payment_code', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('payment_method_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('installments', sa.Text(), nullable=True),
    sa.Column('authorized_at', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('price_lists',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sales_channel_id', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Text(), nullable=True),
    sa.Column('valid_to', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('product_categories',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('depth', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('product_prices',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('price_list_id', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Text(), nullable=True),
    sa.Column('valid_to', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('product_variants',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('package', sa.Text(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('weight_grams', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('products',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('product_code', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('launched_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('purchase_order_items',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('purchase_order_id', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Text(), nullable=True),
    sa.Column('quantity_ordered', sa.Text(), nullable=True),
    sa.Column('unit_cost', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('purchase_orders',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('po_number', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.Text(), nullable=True),
    sa.Column('expected_at', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('refunds',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('refund_code', sa.Text(), nullable=True),
    sa.Column('payment_transaction_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('sales_channels',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('channel_type', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('shipment_items',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('shipment_id', sa.Text(), nullable=True),
    sa.Column('order_item_id', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('shipments',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('shipment_code', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('carrier_id', sa.Text(), nullable=True),
    sa.Column('warehouse_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('tracking_code', sa.Text(), nullable=True),
    sa.Column('freight_amount', sa.Text(), nullable=True),
    sa.Column('shipped_at', sa.Text(), nullable=True),
    sa.Column('estimated_delivery_at', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('stock_reservations',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('reservation_code', sa.Text(), nullable=True),
    sa.Column('warehouse_id', sa.Text(), nullable=True),
    sa.Column('product_variant_id', sa.Text(), nullable=True),
    sa.Column('cart_id', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('released_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('suppliers',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('supplier_code', sa.Text(), nullable=True),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('trade_name', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('payment_terms_days', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('support_agents',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('agent_code', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('hired_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('support_tickets',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('ticket_number', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('shipment_id', sa.Text(), nullable=True),
    sa.Column('assigned_agent_id', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('ticket_events',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    op.create_table('warehouses',
    sa.Column('legacy_row_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('capacity_units', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('legacy_row_id'),
    schema='legacy'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table('warehouses', schema='legacy')
    op.drop_table('ticket_events', schema='legacy')
    op.drop_table('support_tickets', schema='legacy')
    op.drop_table('support_agents', schema='legacy')
    op.drop_table('suppliers', schema='legacy')
    op.drop_table('stock_reservations', schema='legacy')
    op.drop_table('shipments', schema='legacy')
    op.drop_table('shipment_items', schema='legacy')
    op.drop_table('sales_channels', schema='legacy')
    op.drop_table('refunds', schema='legacy')
    op.drop_table('purchase_orders', schema='legacy')
    op.drop_table('purchase_order_items', schema='legacy')
    op.drop_table('products', schema='legacy')
    op.drop_table('product_variants', schema='legacy')
    op.drop_table('product_prices', schema='legacy')
    op.drop_table('product_categories', schema='legacy')
    op.drop_table('price_lists', schema='legacy')
    op.drop_table('payments', schema='legacy')
    op.drop_table('payment_transactions', schema='legacy')
    op.drop_table('payment_methods', schema='legacy')
    op.drop_table('orders', schema='legacy')
    op.drop_table('order_status_history', schema='legacy')
    op.drop_table('order_items', schema='legacy')
    op.drop_table('inventory_movements', schema='legacy')
    op.drop_table('inventory_balances', schema='legacy')
    op.drop_table('goods_receipts', schema='legacy')
    op.drop_table('goods_receipt_items', schema='legacy')
    op.drop_table('delivery_events', schema='legacy')
    op.drop_table('customers', schema='legacy')
    op.drop_table('customer_segments', schema='legacy')
    op.drop_table('customer_preferences', schema='legacy')
    op.drop_table('customer_contacts', schema='legacy')
    op.drop_table('customer_addresses', schema='legacy')
    op.drop_table('coupons', schema='legacy')
    op.drop_table('coupon_redemptions', schema='legacy')
    op.drop_table('carts', schema='legacy')
    op.drop_table('cart_items', schema='legacy')
    op.drop_table('carriers', schema='legacy')
    op.drop_table('campaigns', schema='legacy')
    op.drop_table('brands', schema='legacy')
    # ### end Alembic commands ###

    # AJUSTE MANUAL — simétrico ao upgrade: o schema vazio também sai.
    op.execute(sa.schema.DropSchema('legacy'))
