"""Base declarativa dos modelos da origem transacional.

Os modelos são a **fonte de verdade do schema** (ADR-0009): as migrações são
derivadas deles por `autogenerate` (ADR-0010), e o dicionário de dados é
gerado a partir dos metadados declarados aqui. Nada é escrito à mão em dois
lugares.
"""

from __future__ import annotations

import datetime as dt
from typing import Any

from sqlalchemy import BigInteger, DateTime, Identity, MetaData, Numeric, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Schema da origem transacional. As camadas do armazém vivem em outro banco.
SCHEMA = "oltp"

# ── Classificação de sensibilidade (ADR-0011) ────────────────────────────────
# O vocabulário é inglês por ser identificador técnico: cada valor vira nome de
# policy tag no BigQuery na fase GCP.
PUBLIC = "public"
INTERNAL = "internal"
CONFIDENTIAL = "confidential"
PERSONAL = "personal"

SENSITIVITY_LEVELS = frozenset({PUBLIC, INTERNAL, CONFIDENTIAL, PERSONAL})

#: Dono documental dos dados, conforme os papéis do Termo de Abertura §9.
OWNER = "data_custodian"


def meta(sensitivity: str, description: str, **extra: Any) -> dict[str, Any]:
    """Metadado obrigatório de coluna: classificação e descrição.

    Falha alto e cedo se o nível não existir — um erro de digitação viraria
    uma coluna sem policy tag na fase GCP, que é exatamente o que a política
    de governança existe para impedir.
    """
    if sensitivity not in SENSITIVITY_LEVELS:
        raise ValueError(
            f"nível de sensibilidade desconhecido: {sensitivity!r}. "
            f"Válidos: {sorted(SENSITIVITY_LEVELS)}"
        )
    if not description.strip():
        raise ValueError("descrição de coluna não pode ser vazia")
    return {"sensitivity": sensitivity, "description": description, **extra}


def table_meta(domain: str, description: str, **extra: Any) -> dict[str, Any]:
    """Metadado obrigatório de tabela: domínio e dono (Governança §5.1)."""
    return {"info": {"domain": domain, "owner": OWNER, "description": description, **extra}}


# ── Convenção de nomes ───────────────────────────────────────────────────────
# Sem convenção explícita, o PostgreSQL nomeia constraints sozinho e o Alembic
# não consegue derrubar no `downgrade` o que criou no `upgrade` — a
# reversibilidade exigida pelo ADR-0010 depende disto.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base de todos os modelos da origem transacional."""

    metadata = MetaData(schema=SCHEMA, naming_convention=NAMING_CONVENTION)


# ── Tipos de domínio ─────────────────────────────────────────────────────────
# Valores monetários em decimal, nunca float (CLAUDE.md §3). Dois tipos, porque
# a precisão necessária é diferente: um valor transacionado é arredondado a
# duas casas, um preço unitário não.
Money = Numeric(14, 2)
UnitPrice = Numeric(14, 4)

#: Todo timestamp de evento carrega fuso horário (CLAUDE.md §3).
Timestamp = DateTime(timezone=True)


def pk(description: str = "Chave primária técnica, gerada pelo banco.") -> Any:
    """Chave primária `bigint generated by default as identity`."""
    return mapped_column(
        BigInteger, Identity(always=False), primary_key=True, info=meta(INTERNAL, description)
    )


class TimestampMixin:
    """Marcas de tempo de criação e alteração.

    `updated_at` não é enfeite: é o cursor da carga incremental declarada no
    ADR-0015. Tabela sem ele só pode ser sincronizada por carga completa.
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        Timestamp,
        nullable=False,
        server_default=func.now(),
        info=meta(INTERNAL, "Momento de criação do registro na origem."),
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        Timestamp,
        nullable=False,
        server_default=func.now(),
        info=meta(INTERNAL, "Momento da última alteração; cursor da carga incremental (ADR-0015)."),
    )


class SoftDeleteMixin:
    """Exclusão lógica.

    A origem transacional **nunca apaga fisicamente** (ADR-0015): quem apaga de
    verdade é a origem legada, e a diferença entre as duas é deliberada.
    """

    deleted_at: Mapped[dt.datetime | None] = mapped_column(
        Timestamp,
        nullable=True,
        info=meta(INTERNAL, "Exclusão lógica; nulo enquanto o registro está ativo (ADR-0015)."),
    )


class AppendOnlyMixin:
    """Marca de tempo de registros que só são inseridos.

    Livro de eventos não tem `updated_at` nem `deleted_at`: corrigir um evento
    é inserir outro, compensatório. A carga incremental destas tabelas usa
    `append`, não `dedup + history` (ADR-0015).
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        Timestamp,
        nullable=False,
        server_default=func.now(),
        info=meta(INTERNAL, "Momento em que o evento foi registrado na origem."),
    )


def validate_metadata() -> list[str]:
    """Confere que toda coluna e toda tabela estão classificadas.

    É o que transforma "todo campo classificado" — critério de conclusão da
    Etapa 3 — em asserção verificável, em vez de promessa.
    """
    problems: list[str] = []
    for table in Base.metadata.tables.values():
        info = table.info or {}
        for key in ("domain", "owner", "description"):
            if not info.get(key):
                problems.append(f"{table.name}: tabela sem `{key}`")
        for column in table.columns:
            cinfo = column.info or {}
            if cinfo.get("sensitivity") not in SENSITIVITY_LEVELS:
                problems.append(f"{table.name}.{column.name}: coluna sem `sensitivity` válida")
            if not (cinfo.get("description") or "").strip():
                problems.append(f"{table.name}.{column.name}: coluna sem descrição")
    return problems
